#!/usr/bin/env python3
"""Builds content/games/mechanics/attribution-grid.json (Attribution Grid) from the notes'
governance passages.

    python3 tools/games/build_attribution_grid.py && python3 tools/games/validate_attribution-grid.py

Each spec below cites the .tex line that states the duty (`line`, with a verbatim `ev` phrase
from that passage) and the line that names who holds it (`rev`, optionally in another file,
e.g. LTR-11's corporate treasury is identified as the first line in LTR-9/LTR-6). The role is
only assigned where the notes place the duty-holder cleanly; senior-management-only duties,
model validation / model risk management (LTR-9 l.200-206 says it is not one of the three lines)
and business-area / management committees whose line is not stated are deliberately left out.
source_block is resolved automatically: the nearest block of the reading at or before `line`.
"""
import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
OUT = os.path.join(ROOT, 'content', 'games', 'mechanics', 'attribution-grid.json')
BLOCKS = os.path.join(ROOT, 'content', 'games', 'game-blocks.json')

V1 = 'notes/FRM_Consolidated_Vol1/ch/'
V2 = 'notes/FRM_Consolidated_Vol2/ch/'
F = {
    'ORR-2': V1 + '07_OR_ORR2.tex', 'ORR-3': V1 + '28_OR_ORR3.tex', 'ORR-4': V1 + '32_OR_ORR4.tex',
    'ORR-5': V1 + '29_OR_ORR5.tex', 'ORR-6': V1 + '30_OR_ORR6.tex', 'ORR-7': V1 + '54_OR_ORR7.tex',
    'ORR-9': V1 + '09_OR_ORR9.tex', 'ORR-10': V1 + '33_OR_ORR10.tex', 'ORR-18': V1 + '01_OR_ORR18.tex',
    'ORR-19': V1 + '44_OR_ORR19.tex', 'ORR-20': V1 + '31_OR_ORR20.tex',
    'CR-2': V1 + '48_CR_CR2.tex', 'CR-3': V1 + '49_CR_CR3.tex',
    'LTR-6': V2 + '41_LR_LTR6.tex', 'LTR-9': V2 + '14_LR_LTR9.tex', 'LTR-10': V2 + '15_LR_LTR10.tex',
    'LTR-11': V2 + '43_LR_LTR11.tex', 'LTR-17': V2 + '03_LR_LTR17.tex',
}

ROLES = [
    dict(
        id='first', label='First line',
        responsibility=('Owns and manages the risk it generates. Business units, risk owners and '
                        '(for liquidity) Treasury identify, measure, mitigate and report their own '
                        'risks, put controls in place, and escalate weaknesses to the second line.'),
        examples=['Identifies operational risks and establishes controls (ORR-2)',
                  'Tests the key controls it uses every day (ORR-5)',
                  'Runs root-cause analysis of failures (ORR-4)',
                  'Treasury owns the liquidity stress test model (LTR-9)',
                  'Trains staff to report suspicious transactions (ORR-10)'],
        sources=[dict(file=F['ORR-2'], line=130), dict(file=F['CR-2'], line=22),
                 dict(file=F['ORR-7'], line=45), dict(file=F['LTR-9'], line=194)]),
    dict(
        id='second', label='Second line',
        responsibility=('Oversees the first line independently. Risk management, compliance and '
                        'legal (including the CRO\'s office and the AML/CFT officer) set policies and '
                        'procedures, challenge Line 1\'s measurement and reporting, and aggregate risk data.'),
        examples=['Develops ORM policies and procedures (ORR-2)',
                  'Cross-examines Line 1\'s risk measurement (ORR-2)',
                  'Provides independent oversight of liquidity (LTR-9)',
                  'Acts as AML/CFT contact person, with no business-line duties (ORR-10)',
                  'Advises on credit rather than approving it (CR-2)'],
        sources=[dict(file=F['ORR-2'], line=132), dict(file=F['CR-2'], line=25),
                 dict(file=F['ORR-7'], line=47), dict(file=F['LTR-9'], line=196)]),
    dict(
        id='third', label='Third line',
        responsibility=('Gives independent assurance. Internal audit (and external auditors) review '
                        'controls and adherence to policy, stay strictly separate from other '
                        'departments, and report to internal and external stakeholders.'),
        examples=['Reviews controls and adherence to policies (ORR-2)',
                  'Usually tests controls; ORM only receives the results (ORR-5)',
                  'Periodically reviews the liquidity stress testing framework (LTR-9)',
                  'Audits capital planning data (ORR-20)'],
        sources=[dict(file=F['ORR-2'], line=134), dict(file=F['CR-2'], line=28),
                 dict(file=F['ORR-7'], line=49), dict(file=F['LTR-9'], line=198)]),
    dict(
        id='board', label='Board / committee',
        responsibility=('Sets direction and oversees from above the three lines. The board and its '
                        'risk and audit committees, plus governing committees with delegated oversight '
                        '(ALCO, credit committee), set tolerance, approve frameworks, plans and '
                        'exceptions, and monitor senior management.'),
        examples=['Sets operational risk tolerance and approves the ORMF (ORR-2)',
                  'Approves the capital plan management presents (ORR-20)',
                  'Approves credit guidelines sponsored by the CFO or CRO (CR-2)',
                  'ALCO holds overall responsibility for liquidity stress testing (LTR-9)',
                  'Audit committee receives internal audit reports on controls (ORR-6)'],
        sources=[dict(file=F['ORR-2'], line=104), dict(file=F['ORR-6'], line=18),
                 dict(file=F['LTR-9'], line=192), dict(file=F['CR-2'], line=101)]),
]


def S(rid, line, ev, rev, role, statement, why, conf, why_not):
    """rev = (line, text) in the item's own file, or (file, line, text)."""
    if len(rev) == 2:
        rev = (F[rid], rev[0], rev[1])
    return dict(rid=rid, line=line, ev=ev, rev=rev, role=role, statement=statement, why=why,
                conf=conf, why_not=why_not)


RB2 = (104, 'Board of directors role')
L1_2 = (130, 'The business units or risk owners')
L2_2 = (129, 'Line 2')
L3_2 = (134, 'Internal audit, separate from risk management')

SPECS = [
    # ------------------------------------------------------------------ ORR-2 Risk governance
    S('ORR-2', 110, 'Sets risk tolerance', RB2, 'board',
      "Sets the bank's tolerance for operational risk.",
      "ORR-2's table of what the board owns opens with 'sets risk tolerance' for operational risk.",
      'second', 'Line 2 writes ORM policies and oversees monitoring against tolerance; it does not set the tolerance.'),
    S('ORR-2', 112, 'Approves and updates the ORMF', RB2, 'board',
      'Approves and updates the operational risk management framework (ORMF).',
      'Approving and updating the ORMF is item b of the board\'s operational risk duties.',
      'second', 'Line 2 develops ORM policies and procedures; approving the framework sits above it.'),
    S('ORR-2', 113, 'Ensures policy execution by senior management', RB2, 'board',
      'Ensures that senior management executes the operational risk policy.',
      'ORR-2 lists "ensures policy execution by senior management" among the board\'s duties.',
      'first', 'The business executes the policy day to day; making sure management does so is oversight from the top.'),
    S('ORR-2', 115, 'Promotes a culture of risk management', RB2, 'board',
      'Promotes a firm-wide culture of risk management.',
      'Promoting risk culture is a board duty in ORR-2, and culture is "driven by ethical leadership from the board" (l.201).',
      'second', 'The risk function supports culture, but the notes place promoting it with the board and management at the top.'),
    S('ORR-2', 110, 'Articulates operational resilience goals', RB2, 'board',
      "Articulates the firm's operational resilience goals.",
      'On the resilience side of the board table, the first duty is articulating resilience goals.',
      'second', 'Goals are set at the top; the risk function monitors and reports against them.'),
    S('ORR-2', 113, 'Monitors senior management', RB2, 'board',
      'Monitors senior management on operational resilience.',
      'ORR-2\'s resilience column gives the board the duty to monitor senior management.',
      'third', 'Internal audit assures controls independently; monitoring senior management is listed as a board duty.'),
    S('ORR-2', 115, 'Allocates resources for resilience and ensures training', RB2, 'board',
      'Allocates resources for operational resilience and ensures staff training.',
      'Resource allocation and training for resilience are the board\'s item d in ORR-2.',
      'first', 'Business units run the processes, but deciding the resources for resilience is a board duty.'),
    S('ORR-2', 86, 'oversees all levels of operational risk management', (86, 'the board risk committee'), 'board',
      'Oversees all levels of operational risk management, advising on exposures and making key decisions.',
      'The top level of ORR-2\'s committee structure is the board risk committee, which oversees all levels.',
      'second', 'The risk function oversees Line 1\'s work; oversight of every level, advising the full board, is the board risk committee.'),
    S('ORR-2', 97, 'Committees approve policies and procedures related to ORM', (94, 'Committee Terms of'), 'board',
      'Approves the policies and procedures related to operational risk management, as set out in its terms of reference.',
      'ORR-2: the committee TOR aligns reporting with decisions, and "committees approve policies and procedures related to ORM".',
      'second', 'Line 2 develops ORM policies (l.145); approving them is a committee decision.'),
    S('ORR-2', 139, 'Identify operational risks', L1_2, 'first',
      'Identifies the operational risks generated by its own activities.',
      'Line 1 is the business units or risk owners that generate risk; identifying it is their first listed duty.',
      'second', 'Line 2 cross-examines Line 1\'s work; it does not own the identification.'),
    S('ORR-2', 140, 'Establish controls to manage risks', L1_2, 'first',
      'Establishes controls to manage the risks it generates.',
      'ORR-2 lists "establish controls to manage risks" under Line 1.',
      'second', 'Line 2 writes the ORM policies; the controls themselves are set by the risk owners.'),
    S('ORR-2', 141, 'Evaluate control effectiveness', L1_2, 'first',
      'Evaluates the effectiveness of the controls it operates.',
      'Control-effectiveness evaluation is a Line 1 duty in ORR-2\'s table.',
      'third', 'Internal audit reviews controls independently, but the first evaluation is the owner\'s own.'),
    S('ORR-2', 142, 'Provide oversight and reporting on operational risk within', L1_2, 'first',
      'Provides oversight and reporting on operational risk inside its own unit.',
      'ORR-2 gives Line 1 "oversight and reporting on operational risk within the business line".',
      'second', '"Oversight" tempts Line 2, but Line 2 oversees the bank\'s monitoring functions, not the unit\'s own reporting.'),
    S('ORR-2', 161, 'Escalate control weaknesses and process weaknesses', L1_2, 'first',
      'Escalates control and process weaknesses to the independent risk oversight function.',
      'Escalating control and process weaknesses to Line 2 is how Line 1 relates to the other lines.',
      'second', 'Line 2 receives the escalation; the one escalating is the risk owner.'),
    S('ORR-2', 159, 'Inform Line 2 when unable to perform operational risk', L1_2, 'first',
      'Informs the risk oversight function when it cannot perform its operational risk duties.',
      'ORR-2: Line 1 must inform Line 2 when unable to perform its operational risk duties.',
      'second', 'Line 2 is the one informed, not the one informing.'),
    S('ORR-2', 145, 'Develop ORM policies and procedures', L2_2, 'second',
      'Develops the operational risk management policies and procedures.',
      'Developing ORM policies and procedures is the first Line 2 duty in ORR-2.',
      'board', 'Committees approve ORM policies (l.97); drafting them is Line 2.'),
    S('ORR-2', 146, "Cross-examine Line 1's work", L2_2, 'second',
      "Cross-examines the risk owners' work, including their risk measurement and reporting.",
      'Line 2 provides objective review of Line 1, including cross-examining its measurement and reporting.',
      'third', 'Line 3 reviews controls and policy adherence; routine challenge of Line 1\'s measurement is Line 2.'),
    S('ORR-2', 148, "Oversee the bank's monitoring and reporting functions", L2_2, 'second',
      "Oversees the bank's risk monitoring and reporting functions.",
      'ORR-2 lists overseeing the monitoring and reporting functions under Line 2.',
      'board', 'The board oversees the framework and senior management, not the monitoring functions directly.'),
    S('ORR-2', 149, 'Provide input on major business decisions and regulatory', L2_2, 'second',
      'Provides input on major business decisions and on regulatory compliance.',
      'Line 2 gives input on major business decisions and regulatory compliance (ORR-2).',
      'first', 'Line 1 takes the business decisions; Line 2 contributes the independent risk view.'),
    S('ORR-2', 164, 'Must maintain independence from Line 1', L2_2, 'second',
      'Must maintain independence from the risk owners whose work it reviews.',
      'ORR-2: Line 2 must maintain independence from Line 1.',
      'third', 'Line 3 must be strictly separate from all departments; independence from Line 1 specifically is the Line 2 rule.'),
    S('ORR-2', 152, 'Review controls and adherence to policies and', L3_2, 'third',
      'Reviews controls and adherence to policies and procedures, separately from the risk function.',
      'Line 3 is internal audit, separate from risk management, reviewing controls and policy adherence.',
      'second', 'Line 2 writes and oversees the policies; the independent adherence review is Line 3.'),
    S('ORR-2', 154, 'Maintain its own list of significant risks', L3_2, 'third',
      "Maintains its own list of the bank's significant risks.",
      'ORR-2: Line 3 maintains its own list of significant risks.',
      'second', 'Line 2 aggregates the risk view, but Line 3 keeps its own list so its assurance is not borrowed.'),
    S('ORR-2', 169, 'Assess reliability before relying on work from other', L3_2, 'third',
      "Assesses the reliability of other departments' work before relying on it.",
      'Line 3 must assess reliability before relying on work from other departments.',
      'second', 'Line 2 reviews Line 1 as a matter of course; the reliance test is an assurance-provider\'s rule.'),
    S('ORR-2', 171, 'Provides independent assurance to internal and external', L3_2, 'third',
      'Provides independent assurance to internal and external stakeholders.',
      'Independent assurance to internal and external stakeholders is the defining Line 3 output.',
      'board', 'The board receives assurance; it does not provide it.'),
    S('ORR-2', 168, 'Must be strictly separate from other departments', L3_2, 'third',
      'Must be strictly separate from every other department, including the risk function.',
      'ORR-2: Line 3 must be strictly separate from other departments.',
      'second', 'Line 2 needs independence from Line 1 only; strict separation from all departments is Line 3.'),
    S('ORR-2', 155, 'Occasionally share information with Line 2', L3_2, 'third',
      'Occasionally shares information with the risk oversight function to reduce redundant work.',
      'ORR-2: Line 3 occasionally shares information with Line 2, which may share with Line 3 to reduce redundancies.',
      'first', 'Line 1 escalates to Line 2; the occasional sharing to cut redundancy is between Lines 2 and 3.'),
    # ------------------------------------------------------------------ ORR-6 Risk reporting
    S('ORR-6', 14, "Oversee the firm's risk management framework", (13, 'Risk Committee'), 'board',
      "Oversees the firm's risk management framework and issues directives based on summary exposure reports.",
      'ORR-6: the Risk Committee oversees the framework, receives summary reports and provides directives.',
      'second', 'The central risk function collects and reports the data; the committee receives it and directs.'),
    S('ORR-6', 19, 'Oversees internal controls', (18, 'Audit Committee (Board)'), 'board',
      'Oversees internal controls, receiving independent reports on risk and control effectiveness.',
      'ORR-6 labels this body "Audit Committee (Board)": it oversees internal controls and receives internal audit\'s reports.',
      'third', 'Internal audit writes the reports; the body receiving them is a board committee.'),
    S('ORR-6', 83, "Presented to the board to ensure alignment with the firm's risk appetite",
      (83, 'Presented to the board'), 'board',
      "Reviews risk appetite metrics to confirm the firm stays within its appetite.",
      'ORR-6: risk appetite metrics are presented to the board to ensure alignment with appetite.',
      'second', 'The risk function compiles the KRI metrics; reviewing alignment with appetite happens at the top.'),
    S('ORR-6', 113, 'Identifies upcoming risks and trends for board risk committee reviews',
      (113, 'board risk committee'), 'board',
      'Reviews horizon-scanning reports on emerging risks, regulatory change and market volatility.',
      'ORR-6: emerging-risk and horizon-scanning output is prepared for board risk committee review.',
      'second', 'Preparing the horizon scan is not the same as reviewing it; the review is the board risk committee\'s.'),
    S('ORR-6', 57, 'All you need to know to decide', (61, 'Executive Committee, Board Risk Committee'), 'board',
      'Sits at Tier 3 of the reporting cake: all you need to know to decide.',
      'Tier 3 of ORR-6\'s reporting cake goes to the Executive Committee and Board Risk Committee.',
      'second', 'The operational risk function sits on Tier 2, "all you need to know to act".'),
    S('ORR-6', 28, 'Collects and aggregates risk data', (27, 'Central Risk Function'), 'second',
      'Collects and aggregates firm-wide risk data, reporting it upward and to unit managers.',
      'ORR-6 gives data aggregation to the central risk function, part of the Line 2 structure that oversees monitoring and reporting (ORR-2 l.148).',
      'first', 'Business-line managers monitor their own KRIs; firm-wide aggregation is the central risk function.'),
    S('ORR-6', 168, 'managed by the ORM function using a combined assurance map',
      (F['ORR-5'], 117, 'ORM (2nd line)'), 'second',
      'Manages the combined assurance map that reports risk statuses in green, yellow and red.',
      'ORR-6: combined assurance is owned by the ORM function, which ORR-5 places in the 2nd line.',
      'third', 'Combined assurance coordinates all assurance, audit included, but its owner is the ORM function.'),
    S('ORR-6', 33, 'Front-line monitoring of operational risk data and action plan',
      (32, 'Business Line Managers and Risk Champions'), 'first',
      'Monitors KRIs and action-plan progress, benchmarking its own risks against firm-wide averages.',
      'ORR-6: business-line managers and risk champions do front-line monitoring and benchmark their own risks.',
      'second', 'The central risk function aggregates; monitoring one\'s own KRIs is front-line work.'),
    S('ORR-6', 59, 'All you need to know to monitor', (63, 'Risk Champions, Business-Line Managers'), 'first',
      'Sits at Tier 1 of the reporting cake: all you need to know to monitor.',
      'Tier 1 of the reporting cake goes to risk champions and business-line managers.',
      'second', 'Tier 2, the operational risk function, gets "all you need to know to act".'),
    S('ORR-6', 194, 'Auditors and regulators require proof regarding controls and risk', (194, 'Auditors'), 'third',
      'Requires documentary proof of controls and risk, drawn from records such as meeting minutes.',
      'ORR-6: auditors (and regulators) require proof about controls, which comes from documentation such as committee minutes.',
      'board', 'Committees produce the minutes; the party demanding them as evidence is the auditor.'),
    # ------------------------------------------------------------------ ORR-5 Control testing
    S('ORR-5', 116, 'First line can test key controls they use every day',
      (116, 'First line can test key controls'), 'first',
      'Tests the key controls it uses every day.',
      'ORR-5: the first line can test the key controls it uses every day.',
      'third', 'Internal audit usually tests controls, but ORR-5 allows Line 1 to test its own everyday key controls.'),
    S('ORR-5', 117, 'gets results, not involved in testing itself', (117, 'ORM (2nd line)'), 'second',
      'Receives control-testing results without taking part in the testing.',
      'ORR-5: ORM (2nd line) gets the results and is not involved in testing itself.',
      'third', 'Line 3 usually performs the tests; the function that only receives results is ORM.'),
    S('ORR-5', 118, 'usually tests controls', (118, 'Internal Audit (3rd line)'), 'third',
      'Usually performs the testing of controls.',
      'ORR-5: Internal Audit (3rd line) usually tests controls.',
      'second', 'ORM receives results but is not involved in testing (l.117).'),
    # ------------------------------------------------------------------ ORR-7 ERM structure
    S('ORR-7', 45, 'identify, measure, mitigate, and report risks', (45, 'First line'), 'first',
      'Identifies, measures, mitigates and reports risks as part of daily work.',
      'ORR-7: the first line is business line staff who identify, measure, mitigate and report risks.',
      'second', 'Line 2 monitors risk types and builds tools; the day-to-day handling is Line 1.'),
    S('ORR-7', 47, 'monitor risk types, establish risk tools, and oversee processes', (47, 'Second line'), 'second',
      'Monitors risk types, establishes risk tools and oversees risk processes.',
      'ORR-7: the second line oversees risk management by monitoring risk types and establishing tools.',
      'first', 'Line 1 uses the tools on its own risks; building them and overseeing the process is Line 2.'),
    S('ORR-7', 49, 'evaluate risk management effectiveness', (49, 'Third line'), 'third',
      'Evaluates the effectiveness of enterprise risk management as an independent reviewer.',
      'ORR-7: the third line (internal audit) evaluates risk management effectiveness.',
      'second', 'Line 2 oversees processes; judging whether risk management works is the independent reviewer.'),
    # ------------------------------------------------------------------ ORR-4 / ORR-3
    S('ORR-4', 189, 'Conducted by the first line of defense', (189, 'first line of defense'), 'first',
      "Conducts root-cause analysis of failures, repeatedly asking 'five whys'.",
      'ORR-4: root-cause analysis is conducted by the first line of defense.',
      'third', 'Root-cause investigation is not an audit review; ORR-4 assigns it to the first line.'),
    S('ORR-4', 53, 'reminders, performance metrics, and internal audits', (53, 'internal audits'), 'third',
      'Performs independent reviews that help curb underreporting of operational loss events.',
      'ORR-4 lists internal audits among the strategies that mitigate underreporting of loss data.',
      'second', 'Loss-data collection is run by the risk owners and risk function; the audit check on it is Line 3.'),
    S('ORR-3', 26, 'during Risk and Control Self-Assessment (RCSA)', (27, 'business unit risks'), 'first',
      'Assesses its own risks and controls bottom-up through risk and control self-assessment (RCSA).',
      'ORR-3: bottom-up RCSA involves lower and middle management and focuses on individual business unit risks.',
      'second', 'Line 2 challenges the RCSA; the self-assessment itself is done in the business units.'),
    # ------------------------------------------------------------------ ORR-10 AML/CFT
    S('ORR-10', 36, 'the board of directors must oversee risk policies', (36, 'the board of directors'), 'board',
      'Oversees ML/FT risk policies, AML/CFT risk management activities and compliance.',
      'ORR-10: the board of directors must oversee risk policies, risk management activities and compliance.',
      'second', 'The AML/CFT officer runs and monitors the programme; overseeing it is the board.'),
    S('ORR-10', 37, 'ML/FT risk assessments need clear communication to the', (38, 'board'), 'board',
      "Must receive clear communication of the bank's ML/FT risk assessment.",
      'ORR-10: ML/FT risk assessments need clear communication to the board.',
      'second', 'The AML/CFT officer reports the assessment; the recipient is the board.'),
    S('ORR-10', 50, 'Identify, assess, and control money laundering', (48, '1st Line: Business Units'), 'first',
      'Identifies, assesses and controls money laundering and terrorist financing (ML/FT) risks.',
      'ORR-10\'s table puts identifying, assessing and controlling ML/FT risk in the 1st line: business units.',
      'second', 'The AML/CFT officer monitors and fulfils AML duties; the risk itself is controlled where customers are served.'),
    S('ORR-10', 53, 'Employee training on identifying and reporting suspicious transactions',
      (48, '1st Line: Business Units'), 'first',
      'Trains employees to identify and report suspicious transactions.',
      'ORR-10 lists employee training on suspicious transactions in the business-unit column.',
      'second', 'The AML/CFT officer is the contact person, but ORR-10 puts front-line training with the business units.'),
    S('ORR-10', 52, 'Written policies and procedures for employees', (48, '1st Line: Business Units'), 'first',
      'Keeps written AML/CFT policies and procedures for its employees.',
      'ORR-10\'s 1st-line column includes written policies and procedures for employees.',
      'second', 'Elsewhere Line 2 develops policies (ORR-2), but ORR-10 places employee procedures with the business units.'),
    S('ORR-10', 57, 'Internal and external contact person for AML/CFT issues', (48, '2nd Line: AML/CFT Officer'), 'second',
      'Acts as the internal and external contact person for AML/CFT issues.',
      'ORR-10: the AML/CFT officer (2nd line) is the internal and external contact person.',
      'first', 'Business units apply the controls; the single point of contact is the AML/CFT officer.'),
    S('ORR-10', 58, 'Reports directly to senior management / board', (48, '2nd Line: AML/CFT Officer'), 'second',
      'Reports AML/CFT matters directly to senior management.',
      'ORR-10: the AML/CFT officer reports directly to senior management / board.',
      'board', 'The board is the recipient of the report, not its author.'),
    S('ORR-10', 59, 'Avoids conflicts of interest (no business line responsibilities)',
      (48, '2nd Line: AML/CFT Officer'), 'second',
      'Holds no business-unit responsibilities, so as to avoid conflicts of interest.',
      'ORR-10: the AML/CFT officer avoids conflicts of interest by having no business line responsibilities.',
      'third', 'Line 3 must be separate from all departments; the no-business-duties rule here is written for the AML/CFT officer.'),
    S('ORR-10', 56, 'Monitors and fulfils AML/CFT duties', (48, '2nd Line: AML/CFT Officer'), 'second',
      "Monitors and fulfils the bank's AML/CFT duties as a qualified officer with authority.",
      'ORR-10: a qualified chief AML/CFT officer with authority (l.39) monitors and fulfils AML/CFT duties.',
      'first', 'Business units control ML/FT risk in their activities; monitoring the AML/CFT duties is the officer.'),
    S('ORR-10', 145, 'designate a chief AML/CFT officer for global', (145, 'chief AML/CFT officer'), 'second',
      'Provides global AML/CFT compliance oversight across a cross-border banking group.',
      'ORR-10: cross-border banks designate a chief AML/CFT officer for global compliance oversight.',
      'board', 'The board oversees policy; group-wide compliance oversight is the designated AML/CFT officer.'),
    S('ORR-10', 61, "Regularly audits the bank's AML/CFT policies", (48, '3rd Line: Internal Audits'), 'third',
      "Regularly examines the bank's AML/CFT policies.",
      'ORR-10: the 3rd line regularly audits the bank\'s AML/CFT policies.',
      'second', 'The AML/CFT officer monitors and fulfils the duties; examining the policies periodically is Line 3.'),
    S('ORR-10', 62, 'Ensures effectiveness of AML/CFT controls', (48, '3rd Line: Internal Audits'), 'third',
      'Checks that the AML/CFT controls are effective.',
      'ORR-10: internal audit ensures the effectiveness of AML/CFT controls.',
      'second', 'The officer runs the programme; independent confirmation that controls work is Line 3.'),
    # ------------------------------------------------------------------ ORR-19 / ORR-18 economic capital
    S('ORR-19', 320, 'The board should understand the difference between gross',
      (320, 'The board should understand'), 'board',
      "Understands gross (stand-alone) versus net (diversified) risk when setting the bank's risk tolerance.",
      'ORR-19 (BIS): the board should understand gross vs net risk while setting risk tolerance.',
      'second', 'The risk function measures gross and net risk; setting tolerance on that basis is the board.'),
    S('ORR-19', 419, 'Each business unit within the bank will manage its risk in accordance with',
      (419, 'Each business unit'), 'first',
      'Manages its risk in line with the amount of economic capital allocated to it.',
      'ORR-19: each business unit manages its risk in accordance with its allocated capital.',
      'second', 'Allocation is set centrally; staying within it is the business unit\'s job.'),
    S('ORR-18', 279, 'Business units should regularly submit their capital and risk limit requests',
      (279, 'Business units'), 'first',
      'Regularly submits capital and risk-limit requests for evaluation and adjustment.',
      'ORR-18: business units submit capital and risk-limit requests to the RAROC team and senior management.',
      'second', 'The RAROC team and senior management evaluate the requests; the business units submit them.'),
    # ------------------------------------------------------------------ ORR-20 capital planning
    S('ORR-20', 73, 'Management should present capital plans to the board for approval',
      (73, 'to the board for approval'), 'board',
      'Approves the capital plan that management presents.',
      'ORR-20: management should present capital plans to the board for approval.',
      'first', 'Management prepares and presents the plan; approval is the board\'s.'),
    S('ORR-20', 68, 'Have a board with sufficient expertise to understand capital planning',
      (68, 'Have a board'), 'board',
      'Must have enough expertise to understand the capital planning process.',
      'ORR-20 corporate governance: have a board with sufficient expertise to understand capital planning.',
      'second', 'The risk function has the technical skills; ORR-20\'s expertise requirement is written for the board.'),
    S('ORR-20', 70, 'Provide the board with comprehensive information on risks, losses, models',
      (70, 'Provide the board'), 'board',
      'Receives comprehensive information on risks, losses and models used in capital planning.',
      'ORR-20: provide the board with comprehensive information on risks, losses, models.',
      'second', 'The risk function provides the information; the board receives it.'),
    S('ORR-20', 72, 'Inform the board about stress scenarios and corrective actions',
      (72, 'Inform the board'), 'board',
      'Is kept informed about stress scenarios and the corrective actions planned.',
      'ORR-20: inform the board about stress scenarios and corrective actions.',
      'second', 'The scenarios are designed below; being informed of them and the fixes is the board\'s role.'),
    S('ORR-20', 60, 'Conduct thorough internal audits of capital planning data',
      (60, 'internal audits of capital planning data'), 'third',
      'Conducts thorough independent checks of capital planning data.',
      'ORR-20 internal controls: conduct thorough internal audits of capital planning data.',
      'second', 'Line 2 builds and runs the projections; the thorough independent check of the data is internal audit.'),
    # ------------------------------------------------------------------ ORR-9 Equifax case
    S('ORR-9', 132, 'An internal audit revealed a backlog of', (132, 'An internal audit'), 'third',
      'At Equifax, uncovered a backlog of unpatched vulnerabilities, including the one later exploited.',
      'ORR-9: an internal audit revealed the backlog of unpatched vulnerabilities, including the exploited one.',
      'second', 'Enforcing the patch policy was management\'s failure; the finding itself came from internal audit.'),
    # ------------------------------------------------------------------ CR-2 Governance (credit)
    S('CR-2', 23, 'Primarily own and manage risk', (22, 'Business owners'), 'first',
      'Primarily owns and manages risk, handling daily risks and adherence to guidelines.',
      'CR-2: the first line is the business owners, who primarily own and manage risk.',
      'second', 'Line 2 monitors and oversees; ownership is the defining first-line word.'),
    S('CR-2', 26, 'They establish policies and procedures and serve as', (25, 'Enterprise risk management, compliance, and legal'), 'second',
      'Monitors and oversees risk, setting policies and procedures as management oversight of the risk owners.',
      'CR-2: the second line (ERM, compliance, legal) monitors, oversees and establishes policies and procedures.',
      'board', 'The board approves guidelines; establishing policy and overseeing Line 1 is Line 2 ("own vs oversee vs assure").'),
    S('CR-2', 30, 'Provide independent assurance of the risk management and risk',
      (28, 'Internal audit, external auditors, and special audit'), 'third',
      'Provides independent assurance over both the risk-owning and the risk-monitoring layers of the firm.',
      'CR-2: the third line gives independent assurance of the risk management and monitoring of the first two lines.',
      'second', 'Line 2 monitors risk; assuring that monitoring itself is independent assurance, Line 3.'),
    S('CR-2', 101, 'approved by the Board or its risk committees', (101, 'the Board or its risk committees'), 'board',
      'Approves credit guidelines sponsored by the CFO or CRO.',
      'CR-2: guidelines are typically sponsored by the CFO or CRO and approved by the Board or its risk committees.',
      'second', 'The CRO sponsors and the CRO\'s office maintains the guidelines; approval is at the top.'),
    S('CR-2', 102, 'Periodic reviews by the Board and risk', (102, 'the Board and risk'), 'board',
      'Periodically reviews credit guidelines to keep them current, with event-triggered reviews after losses.',
      'CR-2: periodic reviews by the Board and risk committees keep guidelines current, with event-triggered reviews.',
      'third', 'Internal audit checks adherence; keeping the guidelines up to date is a Board and risk-committee review.'),
    S('CR-2', 106, "Guidelines are typically managed by the CRO's", (156, 'risk management reports to the CRO'), 'second',
      'Manages and maintains the credit guidelines day to day.',
      "CR-2: guidelines are managed by the CRO's office, and risk management reports to the CRO (l.156).",
      'board', 'The Board approves and periodically reviews them; day-to-day management is the CRO\'s office.'),
    S('CR-2', 129, 'Risk management acts in an advisory role', (129, 'Risk management'), 'second',
      'Advises on transactions, focusing on guidance rather than direct approval.',
      'CR-2: risk management acts in an advisory role, focusing on guidance rather than direct approval.',
      'board', 'The CRO and the Board cannot approve all transactions; authority is delegated and the risk function advises.'),
    S('CR-2', 154, 'Risk management should be separate from profit', (154, 'Risk management'), 'second',
      'Stays separate from profit centres, with pay independent of business performance.',
      'CR-2 oversight principle: risk management is separate from profit centres, with independent compensation.',
      'third', 'Line 3 is separate from all departments; this independence rule is written for risk management.'),
    S('CR-2', 161, 'collaborate and attend client meetings when necessary', (160, 'risk managers'), 'second',
      'Attends client meetings and helps originators close deals, while holding a clear final position on limits.',
      'CR-2: risk managers stay close to the business and facilitate deals while remaining independent.',
      'first', 'Closeness to the business does not make it Line 1: independence and a firm position on limits remain.'),
    S('CR-2', 204, 'reviews packages prepared by originators', (204, 'originators'), 'first',
      'Prepares credit packages on high-risk transactions for review before the approval meeting.',
      'CR-2: originators (the business owners of the risk) prepare the packages the credit committee reviews.',
      'second', 'Risk management advises on the package; the originator prepares it.'),
    S('CR-2', 203, 'It approves high-risk loans based on clear guidelines.', (198, 'The credit committee'), 'board',
      'Approves high-risk loans under clear guidelines, by vote, with minutes recorded.',
      'CR-2: the credit committee approves high-risk loans under its charter, with voting and minutes.',
      'second', 'Risk management advises rather than approves (l.129); approval of high-risk loans is the committee.'),
    # ------------------------------------------------------------------ CR-3 Credit risk management
    S('CR-3', 93, 'deviations requiring board approval', (93, 'board approval'), 'board',
      'Approves deviations from the limits set for lending categories.',
      'CR-3: limitations are imposed for lending categories, with deviations requiring board approval.',
      'second', 'The risk function monitors the limits; approving a deviation from them is the board.'),
    S('CR-3', 110, 'including reporting to the board and determining potential losses', (110, 'reporting to the board'), 'board',
      'Receives reporting on loan delinquencies and potential collection losses.',
      'CR-3: monitoring of collections includes reporting delinquencies to the board.',
      'first', 'Lending staff work the delinquencies; the report goes up to the board.'),
    S('CR-3', 428, 'Are lending policies well-organized and clearly defined',
      (419, 'key questions that the board of directors'), 'board',
      'Asks whether lending policies are well organized and whether exceptions are handled consistently.',
      'CR-3 lists these among the key questions the board of directors should ask.',
      'third', 'Internal audit tests adherence; these are the questions CR-3 gives the board to ask.'),
    S('CR-3', 442, 'Is there a sufficient number of skilled personnel',
      (419, 'key questions that the board of directors'), 'board',
      'Asks whether there are enough skilled lending staff for the volume and complexity of lending.',
      'CR-3: staffing adequacy is one of the board\'s key questions on credit risk capacity.',
      'first', 'Lending units do the work; asking whether capacity is adequate is the board\'s question.'),
    S('CR-3', 450, 'Is the flow of information timely', (419, 'key questions that the board of directors'), 'board',
      'Asks whether lending information reaches decision-makers in a timely manner.',
      'CR-3: information flows to senior managers and the Board are part of the board\'s key questions.',
      'second', 'The risk function produces the information; the board asks whether it arrives on time.'),
    S('CR-3', 86, 'Establishing limits for lending officers', (86, 'lending officers'), 'first',
      'Extends credit within individually assigned lending authority limits.',
      'CR-3: banks establish limits for lending officers, with higher limits for more experience.',
      'second', 'Limits are set for the lender; the one extending credit within them is the front-line lending officer.'),
    # ------------------------------------------------------------------ LTR-9 Liquidity stress testing
    S('LTR-9', 192, 'overall responsibility for the liquidity stress testing framework',
      (192, 'Asset-liability committee (ALCO)'), 'board',
      'Holds overall responsibility for the liquidity stress testing framework, under oversight delegated from the top.',
      'LTR-9: the ALCO, with delegated oversight, has overall responsibility for the framework and sits above the three lines.',
      'first', 'Treasury owns the modelling process; overall framework responsibility is the ALCO\'s.'),
    S('LTR-9', 161, 'provide essential information for the asset-liability management committee',
      (161, 'asset-liability management committee'), 'board',
      'Receives the quarterly liquidity stress test reporting package.',
      'LTR-9: stress tests run quarterly and provide essential information for the ALCO.',
      'first', 'Treasury produces the outputs; the quarterly package is reported to the ALCO.'),
    S('LTR-9', 194, 'ownership of the liquidity stress test modelling process', (194, 'first line of defence'), 'first',
      'Owns the liquidity stress test modelling process.',
      'LTR-9: the Treasury unit, first line of defence, owns the stress test modelling process.',
      'second', 'Independent risk management oversees and model risk management validates; Treasury owns the model.'),
    S('LTR-9', 196, 'Responsible for providing independent oversight of liquidity', (196, 'second line of defence'), 'second',
      "Provides independent oversight of the bank's liquidity risk.",
      'LTR-9: the independent risk management function (second line) provides independent oversight of liquidity.',
      'third', 'Oversight is Line 2; Line 3 periodically reviews the framework.'),
    S('LTR-9', 198, 'periodically review the liquidity stress testing framework', (198, 'third line of defence'), 'third',
      'Periodically reviews the liquidity stress testing framework, procedures and controls for compliance with policy and regulation.',
      'LTR-9: internal audit (third line) periodically reviews the framework, procedures and controls.',
      'second', 'Line 2 provides ongoing oversight of liquidity; the periodic review of the whole framework is Line 3.'),
    # ------------------------------------------------------------------ LTR-6 Intraday liquidity
    S('LTR-6', 85, 'first line, owns the risk and runs the position', (85, 'first line'), 'first',
      'Owns intraday liquidity risk and runs the intraday position.',
      'LTR-6: Treasury is the first line, owning the risk and running the position.',
      'board', 'LTR-6 flags naming the ALCO instead of Treasury as the standard wrong answer.'),
    S('LTR-6', 85, 'second line, oversight', (85, 'second line'), 'second',
      'Oversees intraday liquidity risk without running the position itself.',
      'LTR-6: risk management is the second line, providing oversight.',
      'first', 'LTR-6 warns that putting risk management in the first line is the standard trap.'),
    S('LTR-6', 85, 'third line, independent assurance', (85, 'third line'), 'third',
      'Gives independent assurance on how intraday liquidity risk is managed.',
      'LTR-6: internal audit is the third line, giving independent assurance.',
      'second', 'Risk management oversees; independent assurance on the arrangement is internal audit.'),
    # ------------------------------------------------------------------ LTR-11 Contingency funding plan
    S('LTR-11', 78, 'Activates the CFP', (F['LTR-9'], 194, 'Treasury unit'), 'first',
      'Activates the contingency funding plan based on economic analysis and stress test results.',
      'LTR-11: corporate treasury activates the CFP; LTR-9 and LTR-6 place Treasury in the first line.',
      'board', 'The board leads and guides; the management committee approves recommendations; Treasury activates.'),
    S('LTR-11', 78, 'Oversees risk, funding and liquidity in normal circumstances', (F['LTR-6'], 85, 'Treasury'), 'first',
      'Oversees funding and liquidity day to day in normal, non-crisis conditions.',
      'LTR-11: corporate treasury oversees funding and liquidity in normal times; Treasury is the first line (LTR-6).',
      'second', 'Despite the word "oversees", this is Treasury running its own position, the first line.'),
    S('LTR-11', 84, 'Provides leadership to the LCT and management', (84, 'Board of directors'), 'board',
      'Provides leadership and guidance on CFP implementation to the crisis team during a liquidity crisis.',
      'LTR-11: the board of directors leads and guides the LCT and management committee during crises.',
      'first', 'Treasury activates the CFP; leading and guiding is the board\'s verb in LTR-11.'),
    S('LTR-11', 97, 'regulators and supervisors, rating agencies, clearing banks',
      (F['LTR-9'], 194, 'Treasury unit'), 'first',
      'Handles crisis communication with rating agencies and clearing banks.',
      'LTR-11: corporate treasury owns the channel to rating agencies and clearing banks; Treasury is the first line (LTR-9).',
      'second', 'Legal and compliance also face regulators, but rating agencies and clearing banks are treasury\'s channel.'),
    S('LTR-11', 96, 'clients, counterparties', (96, 'Business units'), 'first',
      'Handles crisis communication with clients and counterparties.',
      'LTR-11: in a liquidity crisis, business units own communication with clients and counterparties.',
      'second', 'Legal and compliance face regulators; the client relationship stays with the business units.'),
    # ------------------------------------------------------------------ LTR-10 / LTR-17 ALCO
    S('LTR-10', 36, 'should view this reporting', (36, 'ALCO'), 'board',
      'Views the main regulatory liquidity reports, whose frequency the regulator stipulates.',
      'LTR-10: the regulator stipulates the frequency and the ALCO should view the reporting.',
      'second', 'The regulator sets frequency and the reports are produced below; the governing reviewer is the ALCO.'),
    S('LTR-10', 140, 'should be treated as large by ALCO', (140, 'ALCO'), 'board',
      'Treats any single deposit of 5% of total liabilities as large.',
      'LTR-10: a deposit of 5% of total liabilities should be treated as large by ALCO.',
      'first', 'Relationship managers hold the deposits; the 5% "large" threshold is an ALCO standard.'),
    S('LTR-10', 136, 'Key management information for senior Treasury and relationship managers',
      (136, 'senior Treasury and relationship managers'), 'first',
      'Uses the funding concentration report to avoid over-reliance on any single funding source.',
      'LTR-10: the funding concentration report is key information for senior Treasury and relationship managers.',
      'second', 'Its users are Treasury and relationship managers, both running the funding position (first line).'),
    S('LTR-17', 75, "which meets regularly to manage the firm's interest rate risk",
      (75, 'asset-liability committee (ALCO)'), 'board',
      "Meets regularly to guide asset-liability strategy and manage the firm's interest rate risk.",
      'LTR-17: banks run ALM strategy under an ALCO that meets regularly to manage interest rate risk.',
      'first', 'Treasury executes the ALM strategy; the regular steering body is the ALCO.'),
]


def block_for(readings, rid, file, line):
    best = None
    for o in readings[rid]['objectives']:
        for b in o['blocks']:
            if b.get('source_file') == file and b['source_line'] <= line:
                if best is None or b['source_line'] > best['source_line']:
                    best = b
    return best['id'] if best else None


def main():
    readings = json.load(open(BLOCKS))['readings']
    items, counters = [], {}
    for s in SPECS:
        rid = s['rid']
        counters[rid] = counters.get(rid, 0) + 1
        rfile, rline, rtext = s['rev']
        items.append({
            'id': 'ag-%s-%02d' % (rid, counters[rid]),
            'reading_id': rid,
            'source_block': block_for(readings, rid, F[rid], s['line']),
            'source_file': F[rid],
            'source_line': s['line'],
            'statement': s['statement'],
            'role': s['role'],
            'why': s['why'],
            'confusable_with': s['conf'],
            'why_not': s['why_not'],
            'evidence': s['ev'],
            'role_evidence': {'file': rfile, 'line': rline, 'text': rtext},
        })
    doc = {'version': 1, 'mechanic': 'attribution-grid', 'roles': ROLES, 'items': items}
    with open(OUT, 'w') as fh:
        json.dump(doc, fh, indent=1, ensure_ascii=False)
        fh.write('\n')
    print('wrote %d items to %s' % (len(items), os.path.relpath(OUT, ROOT)))


if __name__ == '__main__':
    sys.exit(main())
