#!/usr/bin/env python3
"""Builder for the Framework Navigator mechanic.

    python3 tools/games/build_framework_navigator.py

Writes content/games/mechanics/framework-navigator.json. Every node item, change and pair
difference carries its own evidence (notes file, line, keywords) so the validator can check it
against the .tex source. Nothing here is invented: frameworks the notes do not date get
year = null, and parent edges say whether the notes make the link explicit ("explicit"),
the child is a component the parent introduced ("component"), or the edge is only the
chronological predecessor in the same lineage ("sequence").

Stdlib only.
"""
import json
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
OUT = os.path.join(ROOT, 'content', 'games', 'mechanics', 'framework-navigator.json')
BLOCKS = os.path.join(ROOT, 'content', 'games', 'game-blocks.json')

V1 = 'notes/FRM_Consolidated_Vol1/ch/'
V2 = 'notes/FRM_Consolidated_Vol2/ch/'
F = {
    'O1': V1 + '13_OR_ORR1.tex', 'O2': V1 + '07_OR_ORR2.tex', 'O4': V1 + '32_OR_ORR4.tex',
    'O10': V1 + '33_OR_ORR10.tex', 'O12': V1 + '18_OR_ORR12.tex', 'O14': V1 + '35_OR_ORR14.tex',
    'O15': V1 + '20_OR_ORR15.tex', 'O16': V1 + '21_OR_ORR16.tex', 'O17': V1 + '43_OR_ORR17.tex',
    'O20': V1 + '31_OR_ORR20.tex', 'O21': V1 + '10_OR_ORR21.tex', 'O22': V1 + '55_OR_ORR22.tex',
    'O23': V1 + '11_OR_ORR23.tex', 'O24': V1 + '12_OR_ORR24.tex',
    'C5': V1 + '02_CR_CR5.tex', 'C7': V1 + '45_CR_CR7.tex', 'C10': V1 + '26_CR_CR10.tex',
    'C14': V1 + '51_CR_CR14.tex', 'C17': V1 + '36_CR_CR17.tex', 'C18': V1 + '52_CR_CR18.tex',
    'CI2': V1 + '04_CI_CI2.tex', 'CI6': V1 + '38_CI_CI6.tex', 'CI8': V1 + '40_CI_CI8.tex',
    'M4': V2 + '35_MR_MR4.tex', 'M18': V2 + '11_MR_MR18.tex',
    'L1': V2 + '01_LR_LTR1.tex', 'L3': V2 + '12_LR_LTR3.tex', 'L9': V2 + '14_LR_LTR9.tex',
    'I9': V2 + '47_IM_IM9.tex', 'I16': V2 + '02_IM_IM16.tex',
}


def rid_of(path):
    """30_MR_MR11.tex -> MR-11; LR_LTR -> LTR-n; OR_ORR -> ORR-n; IM -> IM-n."""
    m = re.search(r'\d+_([A-Z]+)_([A-Z]+?)(\d+)\.tex$', path)
    return '%s-%s' % (m.group(2), m.group(3))


def E(f, line, *kw):
    return {'source_file': F[f], 'source_line': line, 'keywords': list(kw)}


LINEAGES = [
    ('capital', 'Capital adequacy (Basel accords)'),
    ('market', 'Market risk and the trading book'),
    ('counterparty', 'Counterparty risk and OTC derivatives'),
    ('liquidity', 'Liquidity risk'),
    ('oprisk', 'Operational risk and resilience'),
    ('model', 'Model risk'),
    ('stress', 'Supervisory stress testing and capital planning'),
    ('systemic', 'Systemic and structural reform (US)'),
    ('conduct', 'Conduct, investor protection, funds and financial crime'),
    ('insurance', 'Insurance solvency'),
    ('tech', 'Crypto, fintech and AI'),
]

# ---------------------------------------------------------------------------------------------
# Nodes. Items: (text, evidence). Parent links: (parent id, kind, basis, evidence or None).
# ---------------------------------------------------------------------------------------------
NODES = []


def node(id, name, short, year, year_ev, lineage, parents, readings, src, summary,
         introduced=(), restricted=(), responding_to=(), aliases=(), related=()):
    NODES.append(dict(id=id, name=name, short=short, year=year, year_ev=year_ev,
                      lineage=lineage, parents=parents, readings=readings, src=src,
                      summary=summary, introduced=list(introduced),
                      restricted=list(restricted), responding_to=list(responding_to),
                      aliases=list(aliases), related=list(related)))


# ---- capital --------------------------------------------------------------------------------
node('bcbs-1974', 'Basel Committee on Banking Supervision formed', 'BCBS 1974', 1974,
     E('O21', 23, '1974'), 'capital', [], ['ORR-21'], E('O21', 22, 'G10', 'BCBS'),
     'G10 central bankers create the body that writes every later Basel accord.',
     introduced=[
         ('G10 central bankers\' committee for standardised global bank regulation',
          E('O21', 22, 'G10', 'standardised global')),
     ],
     responding_to=[
         ('Self-regulating bank consortiums failed during financial panics',
          E('O21', 12, 'panics')),
         ('1960s-70s trade growth needed coordinated financial regulation',
          E('O21', 14, '1960s', 'coordinated')),
         ('Interconnected global banks posed risks to multiple economies',
          E('O21', 15, 'interconnected global banks')),
     ],
     aliases=['Basel Committee', 'BCBS', '1974'])

node('basel-1', 'Basel I', 'Basel I', 1988, E('O21', 24, '1988'), 'capital',
     [('bcbs-1974', 'explicit', 'The BCBS introduced Basel I in 1988', E('O21', 24, 'Basel I'))],
     ['ORR-21'], E('O21', 24, 'Basel I', '1988'),
     'First global minimum: capital held against credit-risk-weighted assets.',
     introduced=[
         ('Minimum capital requirements based on risk exposures', E('O21', 25, 'minimum capital')),
         ('Tier 1 core and Tier 2 supplementary capital', E('O21', 31, 'Tier 1', 'core capital')),
         ('On-balance-sheet risk weights of 0%, 20%, 50% and 100%',
          E('O21', 105, 'Risk weights')),
         ('Credit conversion factors for off-balance-sheet items',
          E('O21', 98, 'conversion factors')),
         ('Current exposure method: max(V, 0) plus a notional add-on',
          E('O21', 158, 'Current Exposure Method')),
     ],
     restricted=[
         ('Tier 1 capital must exceed 4% of RWA', E('O21', 47, 'Tier 1', '4%')),
         ('Total capital must exceed 8% of RWA', E('O21', 49, 'Total capital', '8%')),
         ('Goodwill subtracted from equity in Tier 1', E('O21', 70, 'goodwill')),
         ('Equity and commodity derivative risk weights capped at 50%',
          E('O21', 204, 'no risk', '50%')),
     ],
     responding_to=[
         ('Need to better gauge bank capital adequacy', E('O21', 24, 'capital adequacy')),
     ],
     aliases=['Basel I', '1988'])

node('basel-2', 'Basel II', 'Basel II', 2006, E('O24', 119, 'Basel II', '2006'), 'capital',
     [('basel-1', 'explicit', 'Basel II answers named Basel I limitations',
       E('O21', 331, 'Basel I limitations'))],
     ['ORR-21', 'ORR-24', 'ORR-1', 'ORR-2', 'CR-10'], E('O21', 336, 'three pillars'),
     'Risk-sensitive capital: ratings, internal models, an op-risk charge and three pillars.',
     introduced=[
         ('Three pillars: minimum capital, supervisory review, market discipline',
          E('O21', 339, 'Pillar 1', 'minimum capital')),
         ('Standardised credit risk weights based on credit ratings',
          E('O21', 367, 'credit ratings')),
         ('IRB capital: one-year 99.9% VaR, net of expected loss',
          E('O21', 405, '99.9')),
         ('First capital charges for operational risk', E('O21', 342, 'operational risk')),
         ('BIA, standardised and AMA routes to op-risk capital',
          E('O21', 513, 'Basic Indicator Approach')),
         ('ICAAP introduced under Pillar 2', E('O21', 346, 'ICAAP')),
         ('Pillar 3 disclosure of capital, exposures and risk measures',
          E('O21', 349, 'disclose')),
         ('Seven Level 1 operational-risk event types', E('O1', 64, 'seven Basel II event')),
         ('Pillar 2 extra capital for concentration, compliance, governance risks',
          E('O2', 35, 'Extra capital', 'concentration')),
     ],
     restricted=[
         ('Kept the 8% total capital ratio', E('O21', 342, '8%')),
         ('OECD status no longer sets risk weights', E('O21', 366, 'OECD')),
         ('IRB probability of default floored at 0.03%', E('O21', 458, '0.03%')),
         ('Foundation IRB LGD fixed: 45% senior, 75% subordinated', E('O21', 460, '45%', '75%')),
         ('Foundation IRB maturity fixed at 2.5 years', E('O21', 463, 'Fixed at 2.5')),
     ],
     responding_to=[
         ('Basel I ignored creditworthiness: every loan weighted 100%',
          E('O21', 332, 'creditworthiness', '100%')),
         ('Basel I ignored diversification and default correlation',
          E('O21', 333, 'diversification')),
     ],
     aliases=['Basel II', '2006'],
     related=['sma', 'solvency-2'])

node('basel-3', 'Basel III', 'Basel III', None, None, 'capital',
     [('basel-2', 'explicit', 'Basel III raised the Basel II 8% minimum to 10.5%',
       E('C5', 125, 'Basel II', 'Basel III'))],
     ['ORR-22', 'CR-5'], E('O22', 114, 'Basel III capital requirements'),
     'Post-crisis rebuild: more and better capital, plus conservation and systemic buffers.',
     introduced=[
         ('Common Equity Tier 1 minimum of 4.5% of RWA', E('O22', 141, '4.5')),
         ('Additional Tier 1 of 1.5%, total Tier 1 6%', E('O22', 149, '1.5', '6')),
         ('Conservation buffer: 7% CET1, 8.5% Tier 1, 10.5% total',
          E('O22', 187, '8.5', '10.5')),
         ('Countercyclical buffer of 0% to 2.5% of RWA', E('O22', 201, '2.5')),
         ('G-SIB buffers of 1% to 3.5%', E('O22', 196, '3.5')),
         ('Categorisation and stricter rules for SIFIs', E('O22', 119, 'systemically important')),
         ('Counterparty credit risk management requirements', E('O22', 124, 'Counterparty credit')),
     ],
     restricted=[
         ('Tier 3 capital eliminated', E('O22', 117, 'Tier 3')),
         ('Focus on tangible Tier 1 capital', E('O22', 118, 'tangible')),
         ('Capital cut for pension deficits and group cross-holdings',
          E('O22', 168, 'pension', 'cross-holdings')),
         ('Limits on exposures to single counterparties', E('O22', 125, 'single counterparties')),
         ('Minimum capital ratio raised from 8% to 10.5%', E('C5', 182, '8', '10.5')),
     ],
     responding_to=[
         ('Banks needing protection in times of financial distress',
          E('O22', 180, 'financial distress')),
         ('Bank cyclicality feeding credit bubbles and instability',
          E('O22', 201, 'cyclicality', 'credit bubbles')),
         ('G-SIB failures\' significant impact on the global system',
          E('O22', 197, 'significant impact')),
     ],
     aliases=['Basel III'],
     related=['leverage-ratio', 'lcr', 'nsfr'])

node('leverage-ratio', 'Basel III leverage ratio', 'Leverage ratio', None, None, 'capital',
     [('basel-3', 'component', 'Basel III introduced leverage ratios',
       E('O22', 121, 'leverage ratios'))],
     ['ORR-22'], E('O22', 215, 'Leverage ratio'),
     'A 3% floor on capital against all exposure, on and off the balance sheet.',
     introduced=[
         ('Ratio of capital to total exposure', E('O22', 215, 'total exposure')),
         ('Exposure includes off-balance-sheet items like loan commitments',
          E('O22', 217, 'loan commitments')),
     ],
     restricted=[
         ('Minimum leverage ratio of 3%', E('O22', 216, '3%')),
     ],
     aliases=['leverage ratio'],
     related=['lcr', 'nsfr', 'basel-3-final'])

node('basel-3-final', 'Basel III finalisation (December 2017 reforms)', 'Basel III 2017', 2017,
     E('O23', 6, '2017'), 'capital',
     [('basel-3', 'explicit', 'The December 2017 reforms revise the Basel III framework',
       E('O23', 4, 'Basel III')),
      ('leverage-ratio', 'explicit', 'The 2017 reforms revise the leverage ratio framework',
       E('O23', 60, 'Leverage ratio framework'))],
     ['ORR-23'], E('O23', 6, 'December 2017'),
     'Constrains internal models: output floor, input floors, fewer model options.',
     introduced=[
         ('Output floor: RWA at least 72.5% of standardised RWA', E('O23', 85, '72.5')),
         ('Input floors for PD, LGD and EAD', E('O23', 38, 'input floors')),
         ('Leverage ratio buffer for G-SIBs, met with Tier 1',
          E('O23', 62, 'leverage ratio buffer', 'Tier 1')),
         ('More granular SA risk weights, e.g. mortgages by LTV',
          E('O23', 29, 'loan-to-value')),
         ('CVA framework aligned with market risk via fair-value sensitivities',
          E('O23', 48, 'market risk framework')),
         ('Leverage exposure better captures derivatives and off-balance-sheet items',
          E('O23', 64, 'derivatives')),
     ],
     restricted=[
         ('Advanced IRB barred for large corporates and financial institutions',
          E('O23', 36, 'large corporates')),
         ('IRB approach for CVA removed', E('O23', 46, 'Removed the IRB approach for CVA')),
         ('Internal models restricted for credit, CVA and op risk',
          E('O23', 12, 'Restricting the use of internal model')),
         ('Reduced reliance on external credit ratings', E('O23', 30, 'external credit ratings')),
     ],
     responding_to=[
         ('Internal-model banks cut capital far below standardised levels',
          E('O23', 72, 'drastically')),
         ('Internal models gave banks an unfair capital advantage',
          E('O23', 73, 'unfair advantage')),
         ('Basel II floor not robust or risk-sensitive enough',
          E('O23', 17, 'Basel II floor')),
     ],
     aliases=['Basel III', '2017'],
     related=['sma', 'frtb'])

# ---- market ---------------------------------------------------------------------------------
node('mra-1996', '1996 Market Risk Amendment', '1996 MRA', 1996, E('O21', 264, '1996'),
     'market',
     [('basel-1', 'explicit', 'An amendment to Basel I adding market risk',
       E('O21', 264, '1996 amendment')),
      ('amend-1995', 'sequence', 'The 1995 amendment had not addressed market risk',
       E('O21', 266, "didn't address market risk"))],
     ['ORR-21', 'MR-4', 'MR-18'], E('O21', 264, '1996 amendment'),
     'Brings trading-book market risk into capital, via VaR models or standard charges.',
     introduced=[
         ('Capital held against market risk from trading activities',
          E('O21', 270, 'market risks from trading')),
         ('Standardised approach with preset charges per trading-book item',
          E('O21', 278, 'pre-set capital charges')),
         ('Internal models: 10-day VaR at 99% confidence', E('O21', 284, '10-day', '99')),
         ('Market RWA = 12.5 x max(VaR(t-1), m x average VaR)', E('O21', 302, '12.5')),
         ('Backtest one-day 99% VaR over the previous 250 days', E('O21', 322, '250')),
         ('Green, yellow and red backtesting zones', E('M4', 309, 'Green', 'Yellow')),
     ],
     restricted=[
         ('Multiplier at least 3, rising to 4 in the red zone',
          E('M4', 301, 'green zone', 'red zone')),
         ('Ten or more exceptions put the bank in the red zone', E('M4', 311, '10 or more')),
         ('Standardised approach ignores correlations between instruments',
          E('O21', 279, 'Ignores correlations')),
     ],
     responding_to=[
         ('1987 crash and VaR\'s popularity exposed market-risk gaps',
          E('O21', 246, '1987', 'market risk gaps')),
         ('The 1995 amendment had not addressed market risk',
          E('O21', 266, "didn't address market risk")),
     ],
     aliases=['1996', 'Market Risk Amendment'],
     related=['basel-2-5', 'frtb'])

node('basel-2-5', 'Basel 2.5 (Basel II.5)', 'Basel 2.5', 2011, E('O22', 19, '2011'), 'market',
     [('mra-1996', 'explicit', 'Stressed VaR added on top of the Basel I VaR measure',
       E('M18', 36, 'in addition to')),
      ('basel-2', 'explicit', 'The response to Basel II in the 2007-2009 crisis',
       E('O22', 16, 'The response'))],
     ['ORR-22', 'MR-18'], E('O22', 19, 'Basel 2.5'),
     'Crisis patch on the 1996 VaR: stressed VaR, IRC for migration, CRM for correlation books.',
     introduced=[
         ('Stressed VaR from a 250-day period of stressed markets',
          E('O22', 20, '250-day')),
         ('Stressed VaR added on top of current VaR', E('M18', 36, 'stressed VaR', 'in addition to')),
         ('Incremental risk charge covering downgrades as well as defaults',
          E('O22', 67, 'downgrades')),
         ('Comprehensive risk measure for correlation-dependent credit products',
          E('O22', 99, 'single capital charge', 'credit correlation')),
         ('IRC liquidity horizons with constant-level-of-risk assumption',
          E('O22', 73, 'Liquidity horizons')),
     ],
     restricted=[
         ('Unrated or below-BB- positions carry a 100% capital charge',
          E('O22', 104, 'unrated', '100')),
         ('Capital adds a multiplied stressed-VaR term to the VaR term',
          E('O22', 36, 'stressed VaR')),
     ],
     responding_to=[
         ('Crisis showed Basel II own estimates underestimated risk',
          E('O22', 11, 'underestimation')),
         ('Low trading-book capital drew risky assets out of the banking book',
          E('O22', 57, 'incentivised')),
         ('Crisis losses from downgrades, spreads, illiquidity, not just defaults',
          E('O22', 65, 'downgrades', 'spread widening')),
     ],
     aliases=['Basel 2.5', 'Basel II.5', 'stressed VaR'],
     related=['frtb', 'mra-1996'])

node('frtb', 'Fundamental Review of the Trading Book', 'FRTB', 2012, E('M18', 20, '2012'),
     'market',
     [('basel-2-5', 'explicit', 'FRTB replaces the Basel II.5 stressed VaR with stressed ES',
       E('M18', 36, 'Basel II.5'))],
     ['MR-18'], E('M18', 20, 'Fundamental Review of the Trading Book'),
     'Rebuilds market-risk capital: stressed ES, liquidity horizons, desk-level model approval.',
     introduced=[
         ('Stressed expected shortfall at 97.5% replaces VaR',
          E('M18', 39, 'Stressed expected shortfall', '97.5')),
         ('Five liquidity horizons: 10, 20, 60, 120, 250 days', E('M18', 157, 'five', '250')),
         ('Nested ES shocks scaled by square root of horizon differences',
          E('M18', 211, 'nested shocks')),
         ('Revised SA: sensitivities, default risk charge, residual risk add-on',
          E('M18', 283, 'Default risk charge', 'Residual risk')),
         ('Seven risk classes, three of them credit spread', E('M18', 317, 'three')),
         ('Desk-level backtesting at both 99% and 97.5%', E('M18', 374, 'Each trading desk')),
         ('P&L attribution tests for bias and noise', E('M18', 394, 'bias', 'noise')),
         ('Default risk charge: 99.9% one-year VaR, equities included',
          E('M18', 443, '99.9', 'equities')),
     ],
     restricted=[
         ('Positions cannot be reclassified between trading and banking books',
          E('M18', 343, 'cannot be reclassified')),
         ('Capital benefit from switching books is disallowed', E('M18', 345, 'disallowed')),
         ('Trading-book entry needs ability to trade and desk risk management',
          E('M18', 334, 'ability to trade', 'physically manages')),
         ('More than 12 (99%) or 30 (97.5%) exceptions force SA',
          E('M18', 375, '30', 'standardized approach')),
         ('PLA breaches on four or more occasions force SA',
          E('M18', 425, 'four or more', 'standardized approach')),
         ('Securitisations must use the standardised approach',
          E('M18', 474, 'standardized approach', 'securitizations')),
         ('IRC constant-risk replacement assumption dropped',
          E('M18', 455, 'without assuming replacement')),
     ],
     responding_to=[
         ('VaR says nothing about losses beyond the threshold', E('M18', 55, 'how bad')),
         ('Lower trading-book capital invited boundary regulatory arbitrage',
          E('M18', 349, 'regulatory arbitrage')),
         ('Own-model CRM gave varying capital for the same portfolio',
          E('M18', 471, 'widely varying')),
     ],
     aliases=['FRTB', 'Fundamental Review', 'Minimum Capital Requirements for Market Risk'],
     related=['basel-2-5', 'mra-1996', 'basel-3-final'])

# ---- counterparty ---------------------------------------------------------------------------
node('amend-1995', '1995 Basel I amendment (netting)', '1995 netting', 1995,
     E('O21', 247, '1995'), 'counterparty',
     [('basel-1', 'explicit', 'Revised Basel I, which had discouraged hedging',
       E('O21', 247, 'Basel I discouraged hedging'))],
     ['ORR-21'], E('O21', 244, 'The 1995 amendment: netting'),
     'Lets banks net bilateral derivative exposures, cutting credit-equivalent amounts.',
     introduced=[
         ('Bilateral netting of credit exposures for regulatory capital',
          E('O21', 250, 'bilateral netting')),
         ('Net replacement ratio: exposure with versus without netting',
          E('O21', 252, 'Net Replacement Ratio')),
         ('Netted add-on: 0.4 x D plus 0.6 x D x NRR', E('O21', 260, '0.4', '0.6')),
         ('Add-on factors for equity and commodity derivatives',
          E('O21', 205, '1995 Amendment', 'add-on')),
         ('Add-on maturity bucket for contracts over five years',
          E('O21', 155, '1995', 'greater than five years')),
     ],
     responding_to=[
         ('Basel I discouraged hedging: no netting recognised',
          E('O21', 247, 'discouraged hedging')),
     ],
     aliases=['1995', 'net replacement ratio', 'NRR'],
     related=['mra-1996', 'g20-2009'])

node('g20-2009', 'G20 Pittsburgh OTC derivatives reforms', 'G20 2009', 2009,
     E('C14', 241, '2009'), 'counterparty',
     [('amend-1995', 'sequence', 'Previous regulatory step on derivative counterparty exposure',
       None)],
     ['CR-14'], E('C14', 237, 'clearing mandate'),
     'G20 commitment to push standardised OTC derivatives through central counterparties.',
     introduced=[
         ('Mandatory central clearing of standardised OTC derivatives',
          E('C14', 247, 'mandatory central clearing')),
         ('Standardised OTC derivatives traded on exchanges or electronic platforms',
          E('C14', 245, 'electronic')),
         ('OTC derivatives reported to trade repositories', E('C14', 248, 'trade repositories')),
     ],
     restricted=[
         ('Higher capital for non-centrally cleared OTC derivatives',
          E('C14', 249, 'higher capital')),
     ],
     responding_to=[
         ('No clear pre-crisis requirement to centrally clear OTC derivatives',
          E('C14', 239, 'no clear requirement')),
         ('Calls for central clearing after Bear Stearns', E('C14', 241, 'Bear Stearns')),
     ],
     aliases=['G20', 'Pittsburgh'],
     related=['dodd-frank', 'bilateral-margin-2011'])

node('bilateral-margin-2011', 'Margin requirements for non-cleared OTC derivatives',
     'Bilat. margin', 2011, E('C17', 361, '2011'), 'counterparty',
     [('g20-2009', 'sequence', 'The G20 followed the clearing mandate with bilateral '
       'collateral rules for non-clearable trades', E('C17', 361, 'G20'))],
     ['CR-17', 'CR-14', 'CR-18'], E('C17', 361, 'bilateral collateral requirements'),
     'Brings CCP-style initial and variation margin to bilateral OTC trades.',
     introduced=[
         ('Collateral requirements for non-clearable OTC derivatives',
          E('C17', 361, 'bilateral collateral')),
         ('Covers both variation and initial margin', E('C17', 364, 'variation', 'initial')),
     ],
     restricted=[
         ('Non-clearable OTC trades carry higher capital requirements',
          E('C17', 360, 'higher')),
     ],
     responding_to=[
         ('Bilateral trades historically had little or no margin',
          E('C14', 295, 'no or only limited')),
         ('Systemic risk and clearable/non-clearable regulatory arbitrage',
          E('C17', 366, 'regulatory arbitrage')),
     ],
     aliases=['G20'],
     related=['g20-2009', 'dodd-frank'])

# ---- liquidity ------------------------------------------------------------------------------
node('bcbs-liq-2008', 'Principles for Sound Liquidity Risk Management and Supervision',
     'Sound Liq 2008', 2008, E('L3', 115, '2008'), 'liquidity', [], ['LTR-3', 'LTR-1'],
     E('L3', 115, 'Principles for Sound Liquidity'),
     'BCBS liquidity principles: governance, measurement, EWIs, contingency funding, disclosure.',
     introduced=[
         ('17 areas of liquidity risk management principles', E('L1', 219, '17 areas')),
         ('Governance, risk tolerance, measurement, funding diversification, stress testing',
          E('L1', 220, 'governance', 'stress testing')),
         ('Contingency funding plan and high-quality liquid assets required',
          E('L1', 221, 'contingency funding plan')),
         ('Bank responsible for sound management of its own liquidity',
          E('L1', 226, 'responsible for the sound management')),
         ('EWIs may be qualitative or quantitative', E('L3', 116, 'qualitative or quantitative')),
         ('EWIs: rapid asset growth, concentrations, currency mismatches',
          E('L3', 118, 'Rapid asset growth')),
         ('Forward-looking metrics on balance sheet and projected cash flows',
          E('L3', 78, 'Principle 5')),
         ('Clear public disclosure and comprehensive supervisory assessment',
          E('L1', 222, 'public disclosures')),
     ],
     aliases=['Sound Principles', 'Sound Liquidity', 'BCBS-2008'],
     related=['lcr', 'nsfr', 'sr-10-6', 'occ-2012', 'bcbs-intraday-2012'])

node('sr-10-6', 'SR 10-6 Interagency Policy Statement on Funding and Liquidity Risk Management',
     'SR 10-6', 2010, E('L3', 145, '2010'), 'liquidity',
     [('bcbs-liq-2008', 'sequence', 'Next supervisory liquidity EWI document in the reading',
       None)],
     ['LTR-3'], E('L3', 145, 'SR 10-6'),
     'Federal Reserve statement: event triggers and staged readiness for liquidity stress.',
     introduced=[
         ('Event triggers alongside early-warning indicators', E('L3', 146, 'event triggers')),
         ('Progressive states of readiness as a stress event evolves',
          E('L3', 146, 'progressive states of readiness')),
         ('EWIs tailored to the firm\'s liquidity risk profile', E('L3', 146, 'tailored')),
         ('Signal: negative publicity about an asset class held',
          E('L3', 148, 'asset class owned')),
     ],
     aliases=['SR 10-6', 'Interagency'],
     related=['occ-2012', 'bcbs-liq-2008'])

node('bcbs-intraday-2012', 'Monitoring Indicators for Intraday Liquidity', 'Intraday 2012',
     2012, E('L3', 133, '2012'), 'liquidity',
     [('bcbs-liq-2008', 'sequence', 'Second BCBS liquidity EWI document, intraday only',
       E('L3', 154, 'BCBS appears twice'))],
     ['LTR-3'], E('L3', 133, 'Monitoring Indicators for Intraday Liquidity'),
     'BCBS monitoring indicators scoped purely to intraday liquidity.',
     introduced=[
         ('Daily maximum liquidity requirement indicator', E('L3', 136, 'Daily maximum')),
         ('Available intraday liquidity indicator', E('L3', 137, 'Available intraday liquidity')),
         ('Total payments and time-specific critical obligations',
          E('L3', 139, 'Time-specific')),
         ('Intraday credit lines extended to FI customers', E('L3', 141, 'credit lines')),
         ('Timing of intraday payments and intraday throughput', E('L3', 142, 'throughput')),
     ],
     aliases=['Monitoring Indicators', 'BCBS-2012'],
     related=['bcbs-liq-2008', 'occ-2012', 'sr-10-6'])

node('occ-2012', 'OCC Comptroller\'s Handbook, Liquidity booklet', 'OCC 2012', 2012,
     E('L3', 102, '2012'), 'liquidity',
     [('sr-10-6', 'sequence', 'Next US supervisory liquidity EWI document in the reading', None)],
     ['LTR-3'], E('L3', 102, 'OCC-2012'),
     'OCC handbook EWIs keyed to embedded product triggers and funding-market signals.',
     introduced=[
         ('EWIs for embedded triggers in callable debt and OTC derivatives',
          E('L3', 103, 'embedded triggers')),
         ('Signal: CAMELS downgrade or pending regulatory action', E('L3', 106, 'CAMELS')),
         ('Signal: counterparties eliminating committed credit lines',
          E('L3', 112, 'committed credit lines')),
         ('Signal: fund providers reluctant to place funds', E('L3', 109, 'Reluctance of trust')),
     ],
     aliases=['OCC', 'Comptroller'],
     related=['sr-10-6', 'bcbs-liq-2008'])

node('lcr', 'Liquidity Coverage Ratio', 'LCR', '2015–2019', E('L1', 209, '2015', '2019'),
     'liquidity',
     [('basel-3', 'component', 'Basel III introduced the LCR', E('L1', 186, 'Basel III introduced')),
      ('bcbs-liq-2008', 'sequence', 'Earlier BCBS liquidity standard (requires HQLA cushion)',
       E('L1', 221, 'high-quality liquid assets'))],
     ['ORR-22', 'LTR-1', 'LTR-9'], E('O22', 218, 'Liquidity Coverage Ratio'),
     'Short-horizon buffer: HQLA must survive 30 days of acute stress.',
     introduced=[
         ('HQLA must cover net cash outflows over 30 stressed days',
          E('O22', 219, '30 days')),
         ('Stress: three-notch downgrade and partial loss of deposits',
          E('L1', 207, 'three notches', 'partial loss of deposits')),
         ('Stress: complete loss of wholesale funding', E('L1', 207, 'wholesale funding')),
         ('Stress: higher secured-funding haircuts and credit-line drawdowns',
          E('L1', 207, 'haircuts', 'drawdowns')),
     ],
     restricted=[
         ('Ratio must be at least 100%', E('O22', 222, '100')),
         ('Phased in: 60% required in 2015, 100% in 2019', E('L1', 209, '60', '2015')),
     ],
     aliases=['LCR', 'Liquidity Coverage', 'HQLA'],
     related=['nsfr', 'leverage-ratio', 'bcbs-liq-2008'])

node('nsfr', 'Net Stable Funding Ratio', 'NSFR', 2018, E('L1', 209, '2018'), 'liquidity',
     [('basel-3', 'component', 'Basel III introduced the NSFR', E('L1', 186, 'Basel III introduced')),
      ('bcbs-liq-2008', 'sequence', 'Earlier BCBS liquidity standard (funding diversification)',
       E('L1', 220, 'diversification of funding'))],
     ['ORR-22', 'LTR-1'], E('O22', 224, 'Net Stable Funding Ratio'),
     'Structural funding test: stable funding must cover a year of funding needs.',
     introduced=[
         ('Available over required stable funding, one-year horizon',
          E('O22', 225, 'one-year')),
         ('ASF factors weight funding by stability (numerator)',
          E('L1', 213, 'ASF', 'numerator')),
         ('RSF factors weight assets by illiquidity (denominator)',
          E('L1', 213, 'RSF', 'harder the asset')),
     ],
     restricted=[
         ('Ratio must be at least 100%', E('O22', 230, '100')),
         ('Implementation date 1 January 2018', E('L1', 209, '1 January 2018')),
     ],
     aliases=['NSFR', 'Net Stable Funding'],
     related=['lcr', 'leverage-ratio', 'bcbs-liq-2008'])

# ---- operational risk -----------------------------------------------------------------------
node('sma', 'Standardised approach for operational risk (SMA)', 'SMA', 2017,
     E('O23', 21, '2017'), 'oprisk',
     [('basel-2', 'explicit', 'Developed to address the shortcomings of Basel II\'s AMA',
       E('O24', 120, "AMA's shortcomings"))],
     ['ORR-24', 'ORR-23', 'ORR-4'], E('O24', 8, 'standardised approach'),
     'Replaces BIA/TSA/AMA with one formula: business indicator scaled by loss history.',
     introduced=[
         ('Business indicator: ILDC plus services plus financial components',
          E('O24', 29, 'ILDC')),
         ('BIC marginal coefficients of 12%, 15% and 18% by bucket',
          E('O24', 52, '0.15', '0.18')),
         ('Internal loss multiplier: losses relative to industry average',
          E('O24', 69, 'industry average')),
         ('Loss component = 15 x average annual loss over 10 years',
          E('O24', 78, '15', '10 years')),
         ('Loss-data criteria: dates, recoveries, causes, independent review',
          E('O24', 150, 'recoveries')),
     ],
     restricted=[
         ('Single standardised approach for all banks', E('O23', 54, 'single Standardized')),
         ('Mandatory modelling for regulatory capital eliminated',
          E('O4', 456, 'eliminates mandatory modelling')),
         ('Bucket 1 banks: capital equals BIC, no ILM', E('O24', 100, 'bucket 1')),
         ('ILM needs at least five years of loss data', E('O24', 83, 'Minimum 5 years')),
         ('Credit risk losses excluded from operational loss data',
          E('O24', 153, 'Exclusion of credit risk')),
     ],
     responding_to=[
         ('AMA lacked comparability across banks', E('O24', 130, 'Lack of comparability')),
         ('AMA calculations were complex', E('O24', 130, 'complex calculations')),
     ],
     aliases=['SMA', 'Standardized Measurement', 'Standardised Measurement', 'AMA'],
     related=['basel-3-final', 'bcbs-opres'])

node('bcbs-opres', 'BCBS Principles for Operational Resilience', 'OpRes princip.', None, None,
     'oprisk', [], ['ORR-1'], E('O1', 185, 'seven principles for operational resilience'),
     'Seven BCBS principles shifting focus from preventing disruption to withstanding it.',
     introduced=[
         ('Seven principles: governance, risk management, incident management, ICT',
          E('O1', 185, 'seven principles', 'ICT')),
     ],
     responding_to=[
         ('Shift from preventing cyber incidents to managing them',
          E('O1', 173, 'preventing cyber incidents')),
     ],
     aliases=['Principles for Operational Resilience'],
     related=['dora', 'sma', 'outsourcing-guidance'])

node('dora', 'Digital Operational Resilience Act (DORA)', 'DORA', None, None, 'oprisk', [],
     ['ORR-1', 'CI-8'], E('CI8', 185, 'Digital Operational Resilience Act'),
     'EU act on ICT risk: third-party and cloud risk, with mandated penetration testing.',
     introduced=[
         ('Focus on ICT third-party risks, including cloud computing',
          E('CI8', 185, 'third-party', 'cloud computing')),
         ('Mandated penetration stress tests', E('CI8', 186, 'penetration stress tests')),
         ('IT requirements for financial institutions', E('O1', 187, 'IT requirements')),
         ('Promotes digital finance while managing its risks', E('O1', 187, 'digital finance')),
     ],
     responding_to=[
         ('Cyber and ICT risks at financial institutions', E('CI8', 167, 'cyber risks and ICT risks')),
     ],
     aliases=['DORA', 'Digital Operational Resilience'],
     related=['bcbs-opres', 'outsourcing-guidance', 'bali-fintech'])

node('outsourcing-guidance', 'Guidance on Managing Outsourcing Risk', 'Outsourcing', None,
     None, 'oprisk', [], ['ORR-12'], E('O12', 1, 'Guidance on Managing Outsourcing Risk'),
     'Supervisory guidance: assess, diligence and contract for third-party service providers.',
     introduced=[
         ('Risk assessment before choosing to outsource', E('O12', 32, 'Risk assessments')),
         ('Due diligence on provider background, finances and controls',
          E('O12', 44, 'Due diligence')),
         ('Seventeen contract provisions, from scope of work to subcontracting',
          E('O12', 140, 'seventeen')),
         ('Right to audit and measurable performance standards',
          E('O12', 88, 'Right to audit')),
     ],
     restricted=[
         ('Foreign providers: home-jurisdiction law governs the contract',
          E('O12', 132, 'jurisdiction')),
         ('Primary provider accountable for subcontractors\' work',
          E('O12', 135, 'accountable')),
         ('Provider liability limits need board and management approval',
          E('O12', 118, 'board and')),
     ],
     responding_to=[
         ('Outsourcing opens compliance, concentration, country and legal risks',
          E('O12', 17, 'Concentration risk')),
     ],
     aliases=['outsourcing'],
     related=['dora', 'model-risk-guidance', 'bcbs-opres'])

# ---- model risk -----------------------------------------------------------------------------
node('model-risk-guidance', 'Supervisory Guidance on Model Risk Management', 'MRM guidance',
     None, None, 'model', [], ['ORR-15', 'ORR-16'],
     E('O15', 1, 'Supervisory Guidance on Model Risk Management'),
     'Supervisory expectations for developing, validating and governing models.',
     introduced=[
         ('Model defined by inputs, processing and reporting components',
          E('O15', 21, 'Information inputs')),
         ('Validation by a team independent of model development',
          E('O15', 53, 'independent of model development')),
         ('Validation includes evaluation of conceptual soundness',
          E('O15', 95, 'conceptual soundness')),
         ('Ongoing monitoring: process verification and benchmarking',
          E('O15', 119, 'Benchmarking')),
         ('Outcomes analysis including backtesting and parallel outcomes',
          E('O15', 131, 'Parallel outcomes')),
         ('Vendor models validated via sensitivity analysis and benchmarking',
          E('O15', 147, 'sensitivity analysis')),
     ],
     restricted=[
         ('Restrictions on model use and continual recalibration',
          E('O15', 57, 'restrictions on model use')),
         ('Revalidation required after major changes', E('O15', 138, 'Revalidation')),
         ('Vendors must provide detailed model information', E('O15', 149, 'vendors')),
     ],
     responding_to=[
         ('Model errors in design, implementation or assumptions', E('O15', 38, 'Model errors')),
         ('Model misuse outside intended scope or changed markets', E('O15', 40, 'Misuse')),
     ],
     aliases=['Model Risk Management', 'MRM'],
     related=['outsourcing-guidance', 'mra-1996', 'frtb'])

# ---- stress testing -------------------------------------------------------------------------
node('scap-2009', 'Supervisory Capital Assessment Program (SCAP)', 'SCAP 2009', 2009,
     E('O17', 131, '2009'), 'stress', [], ['ORR-17'], E('O17', 8, 'SCAP'),
     'US crisis stress test: firm-wide macro scenarios judged on post-stress capital.',
     introduced=[
         ('Broad macro scenarios with multiple factors moving at once',
          E('O17', 17, 'macro-scenarios')),
         ('Whole-firm rather than product-level stress testing', E('O17', 23, 'whole firm')),
         ('Capital adequacy focus: post-stress common equity threshold',
          E('O17', 28, 'common equity threshold')),
         ('Projects revenues and costs as well as losses', E('O17', 31, 'revenues, costs')),
         ('Dynamic, path-dependent stress testing', E('O17', 33, 'path dependent')),
         ('Bank-level projected losses disclosed across eight asset classes',
          E('O17', 133, 'eight asset classes')),
     ],
     responding_to=[
         ('Pre-SCAP tests used single-factor shocks', E('O17', 15, 'single-shocks')),
         ('Earlier tests were static and focused only on losses',
          E('O17', 32, 'static')),
         ('Multi-factor stresses seen in the 2007-2009 crisis', E('O17', 18, '2007')),
     ],
     aliases=['SCAP', 'Supervisory Capital Assessment'],
     related=['ccar', 'eba-2011'])

node('ccar', 'CCAR and the Federal Reserve Capital Plan Rule', 'CCAR', 2011,
     E('O17', 137, '2011'), 'stress',
     [('scap-2009', 'sequence', 'Next US supervisory stress test, compared with the 2009 SCAP',
       E('O17', 139, '2009 SCAP'))],
     ['ORR-17', 'ORR-20'], E('O20', 7, 'Capital Plan Rule'),
     'Annual Fed review of large BHC capital plans under stress.',
     introduced=[
         ('Capital plans required for BHCs above $50 billion', E('O20', 12, '50 billion')),
         ('Supervisory evaluation of BHC capital plans', E('O20', 14, 'evaluates')),
         ('Seven principles of an effective capital adequacy process',
          E('O20', 18, 'seven principles')),
         ('Board and senior management oversight of capital adequacy',
          E('O20', 33, 'board and senior management')),
         ('2012 CCAR: bank-level loss rates by asset class disclosed',
          E('O17', 141, 'SCAP')),
     ],
     restricted=[
         ('2011 CCAR published only macro-scenario results, not bank-level',
          E('O17', 138, 'macro-scenario results')),
     ],
     aliases=['CCAR', 'Comprehensive Capital', 'Capital Plan Rule'],
     related=['scap-2009', 'eba-2011', 'basel-2'])

node('eba-2011', '2011 European (EBA) stress tests', 'EU tests 2011', 2011,
     E('O17', 144, '2011'), 'stress',
     [('ccar', 'explicit', 'Provided extensive detail post-CCAR', E('O17', 145, 'post-CCAR'))],
     ['ORR-17'], E('O17', 144, 'European stress tests'),
     'European tests that rebuilt credibility through detail and downloadable data.',
     introduced=[
         ('Extensive disclosure with downloadable data', E('O17', 147, 'downloadable')),
         ('Irish test compared bank and third-party loss estimates',
          E('O17', 145, 'Irish stress test')),
     ],
     responding_to=[
         ('Earlier, less effective tests had damaged credibility',
          E('O17', 148, 'less effective tests')),
     ],
     aliases=['EBA', 'European Banking', 'European stress'],
     related=['scap-2009', 'ccar'])

# ---- systemic / conduct ---------------------------------------------------------------------
node('adv-act-1940', 'Investment Advisers Act of 1940', 'Advisers Act', 1940,
     E('I9', 173, '1940'), 'conduct', [], ['IM-9'], E('I9', 173, 'Investment Advisers Act'),
     'Pre-crisis US adviser regime whose small-adviser exemption kept hedge funds unregistered.',
     introduced=[
         ('Private adviser exemption: under 15 clients, no SEC registration',
          E('I9', 173, 'fewer than 15 clients')),
     ],
     aliases=['Advisers Act', 'Investment Advisers', '1940'],
     related=['dodd-frank', 'aifmd'])

node('dodd-frank', 'Dodd-Frank Act', 'Dodd-Frank', 2010, E('I9', 173, '2010'), 'systemic',
     [('adv-act-1940', 'explicit', 'Title IV eliminated the Advisers Act private adviser exemption',
       E('I9', 265, 'private adviser exemption'))],
     ['ORR-22', 'ORR-14', 'IM-9', 'CR-7'], E('O14', 33, 'Dodd-Frank'),
     'US post-crisis statute: systemic oversight, Volcker, CFPB, OTC and adviser rules.',
     introduced=[
         ('FSOC to identify risks to the whole financial system', E('O22', 322, 'FSOC')),
         ('SIFIs may be required to hold additional capital', E('O22', 325, 'additional capital')),
         ('Increased OTC derivatives oversight with required clearing',
          E('O22', 328, 'over-the-counter')),
         ('Consumer Financial Protection Bureau (CFPB)', E('O22', 331, 'CFPB')),
         ('Whistleblower protections', E('O14', 34, 'whistleblowers')),
         ('Advisers with $150m+ register with SEC, appoint CCO',
          E('I9', 173, 'Chief Compliance Officer')),
         ('Form PF: annual at $150m AUM, quarterly above $1.5bn',
          E('I9', 271, 'Form PF', 'quarterly')),
         ('Ability-to-repay check; qualified mortgages presumed compliant',
          E('C7', 113, 'ability to repay', 'qualified')),
     ],
     restricted=[
         ('Volcker Rule limits proprietary trading by insured-deposit banks',
          E('O22', 333, 'Volcker', 'proprietary trading')),
         ('Title IV removed the 15-client private adviser exemption',
          E('I9', 265, 'eliminated the private adviser exemption')),
     ],
     responding_to=[
         ('GFC exposed hedge funds\' interconnectedness with banks',
          E('I9', 173, 'interconnectedness')),
         ('Madoff fraud and GFC renewed regulatory pressure', E('I9', 259, 'Madoff')),
         ('The dark side of retail credit risk', E('C7', 109, 'dark side')),
     ],
     aliases=['Dodd-Frank', 'Dodd', 'Volcker', 'Title IV', 'FSOC', 'CFPB'],
     related=['adv-act-1940', 'aifmd', 'mifid-2', 'g20-2009', 'basel-3'])

node('aifmd', 'Alternative Investment Fund Managers Directive (AIFMD)', 'AIFMD', 2010,
     E('I9', 174, '2010'), 'conduct', [], ['IM-9'], E('I9', 174, 'AIFMD'),
     'EU directive regulating alternative fund managers and their leverage.',
     introduced=[
         ('Mandatory registration of fund managers', E('I9', 174, 'mandatory registration')),
         ('Detailed reporting and disclosure', E('I9', 174, 'detailed reporting')),
         ('Marketing rules for EU and non-EU funds targeting EU investors',
          E('I9', 174, 'marketing rules')),
         ('ESMA interprets; member states enforce', E('I9', 174, 'ESMA', 'member states')),
     ],
     restricted=[
         ('Limits on leverage', E('I9', 174, 'limits on leverage')),
     ],
     aliases=['AIFMD', 'Alternative Investment Fund Managers'],
     related=['dodd-frank', 'adv-act-1940', 'mifid-2'])

node('mifid-1', 'MiFID I', 'MiFID I', 2007, E('O14', 25, '2007'), 'conduct', [], ['ORR-14'],
     E('O14', 25, 'MiFID I'),
     'EU conduct baseline: business conduct, disclosure and anti-market-abuse reporting.',
     introduced=[
         ('EU rules for proper business conduct', E('O14', 26, 'business')),
         ('Regulatory disclosure and reporting to prevent market abuse',
          E('O14', 27, 'market abuse')),
     ],
     aliases=['MiFID', 'MiFIR'],
     related=['mifid-2', 'aifmd'])

node('mifid-2', 'MiFID II and MiFIR', 'MiFID II', 2014, E('O14', 29, '2014'), 'conduct',
     [('mifid-1', 'explicit', 'Enhanced the MiFID regime after the crisis',
       E('O14', 30, 'Enhanced regulations'))],
     ['ORR-14', 'IM-16'], E('O14', 29, 'MiFID II'),
     'Post-crisis EU upgrade: pay, conflicts, advice, product governance, best execution, data.',
     introduced=[
         ('Rules on trader and advisor pay and conflicts of interest',
          E('O14', 31, 'conflicts of interest')),
         ('Fair communication and independent advice', E('O14', 31, 'fair communication')),
         ('Sales and product governance, best execution', E('O14', 32, 'best execution')),
         ('Intraday price and volume data for liquid bonds', E('I16', 70, 'Intraday price')),
         ('Mandatory reporting of transaction costs', E('I16', 70, 'transaction costs')),
     ],
     restricted=[
         ('Less-liquid bond data published with a one-month delay', E('I16', 70, 'one-month')),
     ],
     responding_to=[
         ('The 2007-2009 financial crisis', E('O14', 30, '2007')),
     ],
     aliases=['MiFID', 'MiFIR'],
     related=['mifid-1', 'dodd-frank'])

node('aml-bcbs', 'BCBS guidelines on sound management of ML/FT risks', 'BCBS AML', None, None,
     'conduct', [], ['ORR-10'], E('O10', 3, 'Basel Committee'),
     'Basel Committee practices for assessing, mitigating and monitoring ML/FT risk.',
     introduced=[
         ('ML/FT risk assessed at country, sector, bank, customer levels',
          E('O10', 14, 'four levels')),
         ('Qualified chief AML/CFT officer with authority', E('O10', 39, 'chief AML/CFT')),
         ('Three lines: business units, AML/CFT officer, internal audit',
          E('O10', 48, '1st Line', '3rd Line')),
         ('Enhanced due diligence for high-risk customers and PEPs',
          E('O10', 90, 'Enhanced due diligence')),
         ('Identity verification according to FATF recommendations', E('O10', 103, 'FATF')),
         ('Uniform group-wide AML/CFT policies across borders', E('O10', 135, 'Unified policies')),
     ],
     restricted=[
         ('Skipping IT monitoring must be documented and justified',
          E('O10', 71, 'document this decision')),
         ('ID verification still required for numbered accounts',
          E('O10', 124, 'Numbered accounts')),
         ('AML/CFT officer holds no business-line responsibilities',
          E('O10', 59, 'no business line')),
     ],
     aliases=['AML', 'CFT', 'BCBS'],
     related=['mifid-2', 'dodd-frank', 'outsourcing-guidance'])

# ---- insurance / tech -----------------------------------------------------------------------
node('solvency-2', 'Solvency II', 'Solvency II', None, None, 'insurance',
     [('basel-2', 'explicit', 'SCR approaches are modelled on Basel II\'s SA and IRB',
       E('O21', 546, "Basel II's standardized"))],
     ['ORR-21'], E('O21', 534, 'Capital requirements for insurance'),
     'Basel-style two-tier capital regime for insurance companies.',
     introduced=[
         ('Minimum Capital Requirement as the base level', E('O21', 537, 'Minimum Capital Requirement')),
         ('Solvency Capital Requirement: MCR plus capital buffers',
          E('O21', 538, 'Solvency Capital Requirement')),
         ('Standardised or internal-model route to the SCR', E('O21', 544, 'Standardized approach')),
         ('Internal models use one-year VaR at 99.5%', E('O21', 549, '99.5')),
     ],
     aliases=['Solvency II', 'MCR', 'SCR'],
     related=['basel-2', 'mra-1996'])

node('bcbs-crypto', 'BCBS proposed treatment of bank crypto-asset exposures', 'BCBS crypto',
     None, None, 'tech', [], ['CI-6'], E('CI6', 248, 'The BCBS proposal'),
     'Risk-based crypto classification with a punitive weight for higher-risk assets.',
     introduced=[
         ('Risk-based classification of banks\' crypto exposures', E('CI6', 212, 'classification')),
         ('Group 1 lower-risk: weights similar to traditional assets',
          E('CI6', 261, 'Group 1')),
     ],
     restricted=[
         ('Group 2 higher-risk: 1,250% risk weight', E('CI6', 265, '1,250')),
         ('1,250% weight applies to both long and short positions',
          E('CI6', 265, 'both long and short')),
         ('Capital deductions, stricter weights, exposure monitoring',
          E('CI6', 214, 'capital deductions')),
     ],
     responding_to=[
         ('Direct exposure to volatile crypto assets and indirect links',
          E('CI6', 211, 'volatile crypto')),
     ],
     aliases=['BCBS', 'Group 1', 'Group 2'],
     related=['bali-fintech', 'basel-3-final', 'fsb-ai-2024'])

node('bali-fintech', 'Bali Fintech Agenda', 'Bali Fintech', None, None, 'tech', [], ['CI-6'],
     E('CI6', 283, 'Bali Fintech Agenda'),
     'Framework for regulators to organise themselves around fintech and crypto risk.',
     introduced=[
         ('Monitor new crypto developments and technologies', E('CI6', 291, 'Monitoring')),
         ('Prioritise resources to jurisdictions with significant crypto presence',
          E('CI6', 292, 'Prioritising resources')),
         ('Define the scope of what is regulated', E('CI6', 294, 'Scope of regulation')),
         ('Domestic collaboration among regulatory authorities',
          E('CI6', 296, 'Domestic collaboration')),
         ('Continuous risk assessment, often cross-border', E('CI6', 298, 'Continuous risk')),
     ],
     responding_to=[
         ('Fintech risks, including crypto assets and technologies',
          E('CI6', 284, 'fintech risks')),
     ],
     aliases=['Bali', 'BFA'],
     related=['bcbs-crypto', 'fsb-ai-2024'])

node('fsb-ai-2024', 'FSB report: financial stability implications of AI', 'FSB AI 2024', 2024,
     E('CI2', 16, '2024'), 'tech', [], ['CI-2'], E('CI2', 15, 'FSB'),
     'FSB stock-take of AI vulnerabilities, with an agenda for regulators.',
     introduced=[
         ('Regulators to close data gaps on AI use', E('CI2', 401, 'closing data gaps')),
         ('Update regulatory frameworks for AI', E('CI2', 401, 'updating regulatory frameworks')),
         ('Strengthen supervision of AI-related risks', E('CI2', 402, 'strengthening')),
     ],
     responding_to=[
         ('Accelerated AI adoption since the 2017 FSB report', E('CI2', 43, '2017')),
         ('Third-party dependencies and service-provider concentration',
          E('CI2', 10, 'third-party dependencies')),
         ('Market correlations, cyber, model risk, data and governance',
          E('CI2', 11, 'market correlations')),
     ],
     aliases=['FSB', 'Financial Stability Board'],
     related=['dora', 'bali-fintech', 'model-risk-guidance', 'outsourcing-guidance'])

# ---------------------------------------------------------------------------------------------
# Changes: (reading, node, text, decoys, why, evidence)
# ---------------------------------------------------------------------------------------------
CHANGES = [
    ('ORR-21', 'bcbs-1974',
     'G10 central bankers set up a standing committee to standardise global bank regulation.',
     ['basel-1', 'basel-2'], 'The committee was formed first (1974); its first accord came in 1988.',
     E('O21', 22, 'G10')),
    ('ORR-21', 'bcbs-1974',
     'Response to banks interconnected across economies after 1960s-70s trade growth.',
     ['basel-1', 'basel-2'], 'Cross-border banking risk prompted the committee itself, before any accord.',
     E('O21', 14, '1960s')),

    ('ORR-21', 'basel-1',
     'First sets a 4% Tier 1 and 8% total capital minimum against risk-weighted assets.',
     ['basel-2', 'basel-3'], 'Basel I set 4%/8%; Basel II kept the 8%; Basel III raised the total to 10.5%.',
     E('O21', 47, '4')),
    ('ORR-21', 'basel-1',
     'Uninsured residential mortgages get a 50% risk weight; corporate loans 100%.',
     ['basel-2', 'basel-3-final'], 'The fixed four-bucket weight table is Basel I\'s Figure 60.1.',
     E('O21', 110, 'Uninsured residential mortgages')),
    ('ORR-21', 'basel-1',
     'Claims on OECD governments, cash and gold carry a zero risk weight.',
     ['basel-2', 'amend-1995'], 'OECD status drove Basel I weights; Basel II dropped it for ratings.',
     E('O21', 107, 'OECD')),
    ('ORR-21', 'basel-1',
     'Guarantees convert to on-balance-sheet equivalents at 100%, standby letters of credit at 50%.',
     ['amend-1995', 'basel-2'], 'Credit conversion factors are part of the original Basel I rules.',
     E('O21', 122, 'Guarantees')),
    ('ORR-21', 'basel-1',
     'Derivative credit exposure = max(current value, 0) plus a notional-based add-on.',
     ['amend-1995', 'basel-2'], 'The current exposure method came with Basel I; 1995 added netting to it.',
     E('O21', 160, 'current market value')),

    ('ORR-21', 'amend-1995',
     'Bilateral netting of derivative credit exposures is recognised for regulatory capital.',
     ['basel-1', 'mra-1996', 'g20-2009'], 'Basel I discouraged hedging; netting was allowed in 1995.',
     E('O21', 250, 'bilateral netting')),
    ('ORR-21', 'amend-1995',
     'Add-on becomes 0.4 x D plus 0.6 x D x (netted over gross current exposure).',
     ['basel-1', 'mra-1996'], 'The NRR-weighted add-on is the 1995 netting formula.',
     E('O21', 260, '0.4')),
    ('ORR-21', 'amend-1995',
     'Add-on factors introduced for equity and commodity derivatives.',
     ['basel-1', 'mra-1996'], 'Original Basel I did not cover them; the 1995 amendment added add-ons.',
     E('O21', 205, 'add-on factors')),
    ('ORR-21', 'amend-1995',
     'Add-on table gains a maturity bucket for contracts longer than five years.',
     ['basel-1', 'mra-1996'], 'The notes date the extra maturity bucket to the 1995 revision.',
     E('O21', 155, 'greater than five years')),

    ('ORR-21', 'mra-1996',
     'Banks must measure market risk in trading activities and hold capital against it.',
     ['basel-1', 'basel-2-5', 'amend-1995'], 'Market risk capital arrived in 1996; the 1995 step was netting only.',
     E('O21', 270, 'Measure market risks')),
    ('ORR-21', 'mra-1996',
     'Internal models may set capital using 10-day VaR at 99% confidence.',
     ['basel-2-5', 'frtb'], 'Plain 10-day 99% VaR is the 1996 model; 2.5 added stressed VaR, FRTB moved to ES.',
     E('O21', 284, '10-day')),
    ('ORR-21', 'mra-1996',
     'Market RWA equals 12.5 times the larger of yesterday\'s VaR and m times average VaR.',
     ['basel-2-5', 'frtb'], 'This is the 1996 market capital formula; Basel 2.5 adds a stressed-VaR term.',
     E('O21', 302, '12.5')),
    ('ORR-21', 'mra-1996',
     'One-day 99% VaR backtested over 250 days; exceptions raise the capital multiplier.',
     ['frtb', 'basel-2-5'], 'Bank-wide backtesting with a multiplier is 1996; FRTB backtests desk by desk.',
     E('O21', 322, '250')),
    ('MR-4', 'mra-1996',
     'Ten or more backtesting exceptions in a year put the multiplier at 4.',
     ['frtb', 'basel-2-5'], 'The green/yellow/red zones set the multiplier from 3 to 4.',
     E('M4', 311, '10 or more')),
    ('MR-4', 'mra-1996',
     'Zero to four exceptions: green zone, multiplier stays at 3.',
     ['frtb', 'basel-2-5'], 'Green-zone treatment is part of the VaR backtesting rules.',
     E('M4', 309, 'Green')),
    ('MR-18', 'mra-1996',
     'Market risk capital based on VaR with a 10-day horizon and 99% confidence, recent losses only.',
     ['basel-2-5', 'frtb'], 'MR-18 labels this first step "Basel I": VaR on current data.',
     E('M18', 33, '10-day horizon')),

    ('ORR-21', 'basel-2',
     'Credit risk weights now depend on external ratings, not OECD membership.',
     ['basel-1', 'basel-3-final'], 'The Basel II standardised approach made weights rating-based.',
     E('O21', 367, 'credit ratings')),
    ('ORR-21', 'basel-2',
     'Regulators fix LGD at 45% senior and 75% subordinated, and maturity at 2.5 years.',
     ['basel-3-final', 'basel-1'], 'Supervisory LGD and fixed maturity define the foundation IRB approach.',
     E('O21', 460, '45')),
    ('ORR-21', 'basel-2',
     'First explicit capital charge for operational risk, e.g. 15% of average gross income.',
     ['sma', 'basel-1'], 'The Basic Indicator Approach (15%) is Basel II; SMA replaced it later.',
     E('O21', 515, '15')),
    ('ORR-21', 'basel-2',
     'Supervisory review pillar introduces an internal capital adequacy assessment process.',
     ['basel-3', 'basel-1', 'ccar'], 'ICAAP arrives with Pillar 2 of Basel II.',
     E('O21', 345, 'ICAAP')),
    ('ORR-21', 'basel-2',
     'Banks must disclose capital structure, risk exposures and capital allocation to the market.',
     ['basel-3', 'basel-1'], 'Market discipline via disclosure is Pillar 3 of Basel II.',
     E('O21', 349, 'disclose')),
    ('ORR-1', 'basel-2',
     'Operational loss events classified into seven Level 1 event types.',
     ['sma', 'basel-3'], 'The seven event types are the Basel II categories; SMA reuses them.',
     E('O1', 64, 'seven Basel II event')),
    ('ORR-2', 'basel-2',
     'Supervisors may add capital for concentration, compliance and governance risks outside Pillar 1.',
     ['basel-3', 'sma'], 'Pillar 2 of Basel II reaches risks that Pillar 1 does not.',
     E('O2', 35, 'Extra capital')),
    ('CR-10', 'basel-2',
     'IRB capital built on the Vasicek worst-case default rate at a high percentile.',
     ['basel-3-final', 'basel-1'], 'CR-10 ties Vasicek\'s WCDR to the Basel II IRB approach.',
     E('C10', 107, 'Vasicek')),
    ('ORR-24', 'basel-2',
     'Banks may build tailored internal models of operational risk from their own data.',
     ['sma', 'basel-3-final'], 'AMA, part of Basel II (2006), allowed internal op-risk models.',
     E('O24', 123, 'internal models')),

    ('ORR-21', 'solvency-2',
     'Insurers hold a minimum capital requirement plus buffers forming a solvency capital requirement.',
     ['basel-2', 'basel-3'], 'MCR and SCR are the insurance regime, not a bank accord.',
     E('O21', 538, 'Solvency Capital Requirement')),
    ('ORR-21', 'solvency-2',
     'Internal-model capital uses one-year VaR at 99.5% confidence.',
     ['basel-2', 'mra-1996'], '99.5% one-year is the insurance internal model; Basel IRB uses 99.9%.',
     E('O21', 549, '99.5')),

    ('ORR-22', 'basel-2-5',
     'VaR must also be computed on a 250-day period of stressed market conditions.',
     ['mra-1996', 'frtb'], 'Stressed VaR is Basel 2.5; FRTB later uses stressed ES instead.',
     E('O22', 20, '250-day')),
    ('ORR-22', 'basel-2-5',
     'Trading-book default charge widened to capture downgrades and spread risk, not only defaults.',
     ['frtb', 'mra-1996'], 'The IRC expanded the IDRC after crisis losses came from downgrades.',
     E('O22', 66, 'Incremental Risk Charge')),
    ('ORR-22', 'basel-2-5',
     'A single charge for correlation-dependent credit products such as ABS and CDOs.',
     ['frtb', 'basel-3'], 'The comprehensive risk measure was introduced in Basel 2.5.',
     E('O22', 102, 'collateralised debt obligations')),
    ('ORR-22', 'basel-2-5',
     'Unrated or below BB- correlation positions need dollar-for-dollar capital.',
     ['frtb', 'mra-1996'], 'The 100% charge sits inside the Basel 2.5 CRM.',
     E('O22', 105, 'dollar-for-dollar')),
    ('MR-18', 'basel-2-5',
     'Banks may use their own approved models for the securitisation correlation charge.',
     ['frtb', 'basel-2'], 'Own-model CRM was Basel II.5; FRTB withdrew it.',
     E('M18', 469, 'own models')),
    ('MR-18', 'basel-2-5',
     'A stressed measure is added alongside, not instead of, the current VaR.',
     ['frtb', 'mra-1996'], 'Basel II.5 keeps current VaR and adds stressed VaR on top.',
     E('M18', 36, 'in addition to')),

    ('MR-18', 'frtb',
     'Capital measure switches to expected shortfall at 97.5% over a stressed period.',
     ['basel-2-5', 'mra-1996'], 'Both the measure (ES) and the confidence (97.5%) change here.',
     E('M18', 39, '97.5')),
    ('MR-18', 'frtb',
     'Five liquidity horizons from 10 to 250 days assigned by asset category.',
     ['basel-2-5', 'mra-1996'], 'Category liquidity horizons belong to the FRTB ES calculation.',
     E('M18', 157, 'five')),
    ('MR-18', 'frtb',
     'Once booked, positions cannot move between trading and banking book without keeping original capital.',
     ['basel-2-5', 'basel-3-final'], 'The fixed boundary and disallowed benefit target regulatory arbitrage.',
     E('M18', 343, 'cannot be reclassified')),
    ('MR-18', 'frtb',
     'A desk with more than 12 exceptions at 99% loses internal-model approval.',
     ['mra-1996', 'basel-2-5'], 'Desk-level backtesting with SA fallback is FRTB, not the 1996 bank-wide zones.',
     E('M18', 371, '12')),
    ('MR-18', 'frtb',
     'Bias ratio of unexplained to actual P&L must stay within plus or minus 10%.',
     ['mra-1996', 'basel-2-5'], 'P&L attribution is an FRTB model-eligibility test.',
     E('M18', 410, '10')),
    ('MR-18', 'frtb',
     'Securitisations must use the standardised approach; internal models withdrawn.',
     ['basel-2-5', 'basel-3-final'], 'The motivation was inconsistent capital across banks, not leniency.',
     E('M18', 474, 'standardized approach')),
    ('MR-18', 'frtb',
     'Jump-to-default charge at 99.9% one-year VaR now applies to equities too.',
     ['basel-2-5', 'mra-1996'], 'The IDR charge covering all risk assets is FRTB\'s credit change.',
     E('M18', 443, '99.9')),
    ('MR-18', 'frtb',
     'Drops the assumption that deteriorated credit positions are replaced to keep risk constant.',
     ['basel-2-5', 'mra-1996'], 'The constant-level-of-risk assumption was Basel 2.5 IRC; FRTB drops it.',
     E('M18', 455, 'replacement')),

    ('ORR-22', 'basel-3',
     'Common equity Tier 1 must be at least 4.5% of risk-weighted assets.',
     ['basel-1', 'basel-2', 'basel-3-final'], 'The CET1 layer and its 4.5% minimum come with Basel III.',
     E('O22', 141, '4.5')),
    ('ORR-22', 'basel-3',
     'Tier 3 capital eliminated; focus shifts to tangible Tier 1.',
     ['basel-3-final', 'basel-2'], 'Capital-quality changes were the first Basel III step.',
     E('O22', 117, 'Tier 3')),
    ('ORR-22', 'basel-3',
     'Buffer of 0% to 2.5% of RWA set according to the economic cycle.',
     ['basel-3-final', 'basel-2'], 'The countercyclical buffer is Basel III.',
     E('O22', 201, '2.5')),
    ('ORR-22', 'basel-3',
     'Normal-times minimums become 7% core equity, 8.5% Tier 1 and 10.5% total capital.',
     ['basel-3-final', 'basel-2'], 'These include the capital conservation buffer.',
     E('O22', 187, '8.5')),
    ('ORR-22', 'basel-3',
     'Global systemically important banks hold extra capital buffers of 1% to 3.5%.',
     ['basel-3-final', 'basel-2'], 'G-SIB risk-based buffers are Basel III; 2017 added a G-SIB leverage buffer.',
     E('O22', 196, '3.5')),
    ('ORR-22', 'basel-3',
     'Capital adjusted downward for pension plan deficits and group cross-holdings.',
     ['basel-2', 'basel-3-final'], 'Stricter capital definitions are part of Basel III.',
     E('O22', 168, 'pension')),
    ('CR-5', 'basel-3',
     'Minimum capital ratio raised from 8% to 10.5%.',
     ['basel-2', 'basel-3-final'], 'CR-5: 8% under Basel II, 10.5% under Basel III.',
     E('C5', 182, '10.5')),

    ('ORR-22', 'leverage-ratio',
     'Capital over total exposure, including off-balance-sheet loan commitments, must be at least 3%.',
     ['lcr', 'nsfr', 'basel-3-final'], 'A 3% capital-to-exposure floor, not a liquidity ratio.',
     E('O22', 216, '3')),

    ('ORR-23', 'basel-3-final',
     'Total RWA must be at least 72.5% of RWA computed under standardised approaches.',
     ['basel-3', 'basel-2', 'frtb'], 'The revised output floor came with the December 2017 reforms.',
     E('O23', 85, '72.5')),
    ('ORR-23', 'basel-3-final',
     'Advanced IRB withdrawn for large corporates and financial institutions; foundation IRB required.',
     ['basel-2', 'basel-3'], 'Restricting internal models was the 2017 theme.',
     E('O23', 36, 'large corporates')),
    ('ORR-23', 'basel-3-final',
     'Floors imposed on bank-estimated PD, LGD and EAD inputs.',
     ['basel-2', 'basel-3'], 'Basel II floored only PD (0.03%); 2017 floors all three inputs.',
     E('O23', 38, 'input floors')),
    ('ORR-23', 'basel-3-final',
     'IRB approach for CVA risk removed; only standardised or basic approaches remain.',
     ['basel-3', 'frtb'], 'Removing CVA internal models is part of the 2017 package.',
     E('O23', 46, 'IRB approach for CVA')),
    ('ORR-23', 'basel-3-final',
     'Global systemically important banks get an extra Tier 1 buffer on the capital-to-exposure ratio.',
     ['basel-3', 'leverage-ratio'], 'The G-SIB leverage buffer was added in 2017, after the 3% ratio.',
     E('O23', 62, 'G-SIBs')),
    ('ORR-23', 'basel-3-final',
     'Residential mortgage risk weights vary with loan-to-value under the standardised approach.',
     ['basel-2', 'basel-1'], 'Granular SA weights were a 2017 revision.',
     E('O23', 29, 'loan-to-value')),
    ('ORR-23', 'basel-3-final',
     'Securitisation in the floor: SEC-ERBA, SEC-SA or a 1,250% risk weight.',
     ['frtb', 'basel-3'], 'These are the output-floor approaches for securitisation.',
     E('O23', 113, 'SEC-ERBA')),

    ('ORR-24', 'sma',
     'Op-risk capital built from a business indicator times bucket coefficients of 12%, 15%, 18%.',
     ['basel-2', 'basel-3-final'], 'Marginal BI coefficients define the business indicator component.',
     E('O24', 52, '0.15')),
    ('ORR-24', 'sma',
     'Loss component equals 15 times average annual operational loss over ten years.',
     ['basel-2', 'basel-3-final'], 'The loss component feeds the internal loss multiplier.',
     E('O24', 78, '15')),
    ('ORR-24', 'sma',
     'Banks in the smallest size bucket hold capital equal to the BI component alone.',
     ['basel-2', 'basel-3-final'], 'Bucket 1 banks skip the internal loss multiplier.',
     E('O24', 100, 'bucket 1')),
    ('ORR-24', 'sma',
     'Without five years of loss data, no internal loss multiplier is possible.',
     ['basel-2', 'basel-3-final'], 'The five-year data minimum is a condition of the new approach.',
     E('O24', 83, 'Minimum 5')),
    ('ORR-4', 'sma',
     'Mandatory modelling for regulatory op-risk capital ends; modelling shifts to Pillar 2 ICAAP.',
     ['basel-2', 'bcbs-opres'], 'Replacing AMA removed modelling from Pillar 1 op-risk capital.',
     E('O4', 456, 'mandatory modelling')),
    ('ORR-23', 'sma',
     'All banks use one standardised op-risk approach based on income and historical losses.',
     ['basel-2', 'basel-3'], 'The single op-risk approach is part of the December 2017 revisions.',
     E('O23', 54, 'single Standardized')),

    ('ORR-22', 'lcr',
     'High-quality liquid assets must cover net cash outflows over a 30-day stress period.',
     ['nsfr', 'bcbs-liq-2008', 'leverage-ratio'], '30 days and HQLA mark the short-horizon ratio.',
     E('O22', 219, '30 days')),
    ('LTR-1', 'lcr',
     'Stress scenario: three-notch downgrade, partial deposit loss, complete loss of wholesale funding.',
     ['nsfr', 'sr-10-6'], 'This acute 30-day scenario defines the short-horizon ratio.',
     E('L1', 207, 'three notches')),
    ('LTR-1', 'lcr',
     'Phased in from 60% in 2015 to 100% in 2019.',
     ['nsfr', 'leverage-ratio'], 'The other ratio had a single 1 January 2018 start date.',
     E('L1', 209, '60')),
    ('LTR-9', 'lcr',
     'Tactical current-position metric: available liquidity against 30-day net cash outflows.',
     ['nsfr', 'bcbs-intraday-2012'], 'LTR-9 lists this ratio among current liquidity position metrics.',
     E('L9', 171, 'tactical')),

    ('ORR-22', 'nsfr',
     'Available stable funding must cover required stable funding over a one-year period.',
     ['lcr', 'bcbs-liq-2008', 'leverage-ratio'], 'One-year structural funding, not a 30-day buffer.',
     E('O22', 225, 'one-year')),
    ('LTR-1', 'nsfr',
     'Liabilities weighted by stability in the numerator; assets by how hard they are to liquidate.',
     ['lcr', 'leverage-ratio'], 'ASF on funding (numerator), RSF on assets (denominator).',
     E('L1', 213, 'harder the asset')),
    ('LTR-1', 'nsfr',
     'Implemented on 1 January 2018.',
     ['lcr', 'basel-3-final'], 'The other liquidity ratio phased in over 2015-2019.',
     E('L1', 209, '1 January 2018')),

    ('LTR-1', 'bcbs-liq-2008',
     'Seventeen principle areas: governance, risk tolerance, measurement, funding diversification, stress testing.',
     ['sr-10-6', 'lcr', 'occ-2012'], 'The BIS/BCBS principles cover 17 areas.',
     E('L1', 219, '17')),
    ('LTR-3', 'bcbs-liq-2008',
     'Early-warning indicators may be qualitative or quantitative, e.g. rapid asset growth.',
     ['occ-2012', 'sr-10-6', 'bcbs-intraday-2012'], 'The general firm-level EWI list with that wording is BCBS-2008.',
     E('L3', 116, 'qualitative or quantitative')),
    ('LTR-3', 'bcbs-liq-2008',
     'Use forward-looking metrics on balance-sheet structure and projected cash flows.',
     ['sr-10-6', 'occ-2012'], 'This is Principle 5 of the BCBS Sound Principles.',
     E('L3', 78, 'Principle 5')),
    ('LTR-1', 'bcbs-liq-2008',
     'A bank owns its liquidity risk: robust framework, contingency funding plan and unencumbered liquid-asset cushion.',
     ['sr-10-6', 'occ-2012', 'lcr'], 'The first principle: the bank owns, the supervisor assesses.',
     E('L1', 226, 'responsible')),

    ('LTR-3', 'sr-10-6',
     'Early-warning indicators paired with event triggers tailored to the firm\'s liquidity profile.',
     ['bcbs-liq-2008', 'occ-2012'], 'Event triggers are the Federal Reserve document\'s discriminator.',
     E('L3', 146, 'event triggers')),
    ('LTR-3', 'sr-10-6',
     'The firm moves through progressive states of readiness as a liquidity event evolves.',
     ['bcbs-liq-2008', 'occ-2012'], 'Progressive readiness is the Federal Reserve statement\'s language.',
     E('L3', 146, 'progressive states')),

    ('LTR-3', 'bcbs-intraday-2012',
     'Monitoring indicator: the daily maximum liquidity requirement.',
     ['bcbs-liq-2008', 'occ-2012'], 'Intraday-only indicators belong to the 2012 BCBS document.',
     E('L3', 136, 'Daily maximum')),
    ('LTR-3', 'bcbs-intraday-2012',
     'Track intraday throughput and the timing of intraday payments.',
     ['bcbs-liq-2008', 'sr-10-6'], 'Throughput and payment timing are intraday indicators.',
     E('L3', 142, 'throughput')),
    ('LTR-3', 'bcbs-intraday-2012',
     'Monitor intraday credit lines extended to financial-institution customers.',
     ['bcbs-liq-2008', 'occ-2012'], 'Another intraday-only indicator.',
     E('L3', 141, 'credit lines')),

    ('LTR-3', 'occ-2012',
     'Warning signs when embedded triggers in callable debt or OTC derivatives near breach.',
     ['bcbs-liq-2008', 'sr-10-6'], 'Embedded product triggers are the OCC discriminator.',
     E('L3', 103, 'embedded triggers')),
    ('LTR-3', 'occ-2012',
     'A CAMELS component or composite rating downgrade counts as an early-warning indicator.',
     ['bcbs-liq-2008', 'sr-10-6'], 'CAMELS is a US bank rating; this EWI is in the OCC list.',
     E('L3', 106, 'CAMELS')),
    ('LTR-3', 'occ-2012',
     'Reluctance of trust managers, money managers and public entities to place funds.',
     ['bcbs-liq-2008', 'sr-10-6'], 'This credit-sensitive fund-provider EWI is on the OCC list.',
     E('L3', 109, 'trust managers')),

    ('CR-14', 'g20-2009',
     'Standardised OTC derivatives must be centrally cleared and traded on exchanges or electronic platforms.',
     ['bilateral-margin-2011', 'amend-1995'], 'The 2009 leaders\' commitment after Bear Stearns.',
     E('C14', 247, 'mandatory central clearing')),
    ('CR-14', 'g20-2009',
     'OTC derivative trades must be reported to trade repositories.',
     ['bilateral-margin-2011', 'dodd-frank'], 'Trade reporting was one of the 2009 commitments.',
     E('C14', 248, 'trade repositories')),

    ('CR-17', 'bilateral-margin-2011',
     'Initial and variation margin extended to OTC derivatives that cannot be centrally cleared.',
     ['g20-2009', 'amend-1995'], 'Bilateral collateral rules followed the clearing mandate in 2011.',
     E('C17', 361, 'bilateral collateral')),
    ('CR-17', 'bilateral-margin-2011',
     'Aims to cut regulatory arbitrage between clearable and non-clearable OTC trades.',
     ['g20-2009', 'dodd-frank'], 'Margin on non-cleared trades removes the incentive to avoid clearing.',
     E('C17', 366, 'regulatory arbitrage')),
    ('CR-14', 'bilateral-margin-2011',
     'Bilateral trades, historically lightly margined, get margin rules similar to central clearing.',
     ['g20-2009', 'amend-1995'], 'Margin for bilateral trades is the non-cleared regime.',
     E('C14', 297, 'bilateral trades')),
    ('CR-18', 'bilateral-margin-2011',
     'Bespoke credit-based bilateral margining starts giving way to regulatory rules.',
     ['g20-2009', 'amend-1995'], 'CR-18: bilateral margining with regulatory rules being introduced.',
     E('C18', 211, 'regulatory rules being introduced')),

    ('ORR-22', 'dodd-frank',
     'A council is created to identify and address risks to the entire financial system.',
     ['g20-2009', 'basel-3'], 'FSOC was created by the US post-crisis statute.',
     E('O22', 322, 'Financial')),
    ('ORR-22', 'dodd-frank',
     'Banks that accept insured deposits face limits on proprietary trading.',
     ['basel-3', 'mifid-2'], 'The Volcker Rule is part of the US statute.',
     E('O22', 334, 'proprietary trading')),
    ('ORR-22', 'dodd-frank',
     'A consumer financial protection bureau ensures clear and fair consumer lending.',
     ['mifid-2', 'basel-3'], 'CFPB was established by the US statute.',
     E('O22', 331, 'Consumer')),
    ('IM-9', 'dodd-frank',
     'Hedge fund advisers with at least $150 million must register with the SEC and appoint a CCO.',
     ['adv-act-1940', 'aifmd'], 'The US post-GFC statute regulates the adviser.',
     E('I9', 173, '150 million')),
    ('IM-9', 'dodd-frank',
     'The 15-client private adviser exemption is eliminated.',
     ['adv-act-1940', 'aifmd'], 'Title IV removed the exemption that the 1940 regime created.',
     E('I9', 265, 'private adviser exemption')),
    ('IM-9', 'dodd-frank',
     'Funds with more than $1.5 billion AUM file systemic-risk reports quarterly.',
     ['aifmd', 'adv-act-1940'], 'Form PF filing thresholds came with the US statute.',
     E('I9', 272, '1.5 billion')),
    ('CR-7', 'dodd-frank',
     'Mortgage originators must verify ability to repay; qualified mortgages are presumed compliant.',
     ['basel-3', 'mifid-2'], 'CFPB rules from the US statute address retail credit risk.',
     E('C7', 113, 'ability to repay')),
    ('ORR-14', 'dodd-frank',
     'US statute protecting whistleblowers and regulating OTC derivatives.',
     ['mifid-2', 'g20-2009'], 'Whistleblower protection is in the US statute, not MiFID.',
     E('O14', 34, 'whistleblowers')),

    ('IM-9', 'adv-act-1940',
     'Advisers with fewer than 15 clients are exempt from SEC registration.',
     ['dodd-frank', 'aifmd'], 'The exemption dates from the 1940 regime; Dodd-Frank removed it.',
     E('I9', 173, 'fewer than 15')),

    ('IM-9', 'aifmd',
     'EU rules require manager registration, detailed reporting and leverage limits for alternative funds.',
     ['dodd-frank', 'mifid-2'], 'The EU regulates the manager and the leverage.',
     E('I9', 174, 'limits on leverage')),
    ('IM-9', 'aifmd',
     'Marketing rules for non-EU funds targeting EU investors; member states enforce.',
     ['mifid-2', 'dodd-frank'], 'ESMA interprets the directive; member states enforce it.',
     E('I9', 174, 'marketing rules')),

    ('ORR-14', 'mifid-1',
     'EU rules on proper business conduct, disclosure and reporting to prevent market abuse.',
     ['mifid-2', 'aifmd'], 'The 2007 original set the conduct baseline.',
     E('O14', 26, 'business conduct')),
    ('ORR-14', 'mifid-2',
     'Post-crisis EU rules on trader pay, conflicts of interest and best execution.',
     ['mifid-1', 'dodd-frank'], 'The 2014 revision added pay, conflicts and best-execution rules.',
     E('O14', 31, 'conflicts of interest')),
    ('IM-16', 'mifid-2',
     'Intraday bond price and volume data, with a one-month delay for less liquid bonds.',
     ['mifid-1', 'dodd-frank'], 'IM-16 attributes this data regime to the 2014 EU rules.',
     E('I16', 70, 'one-month')),
    ('IM-16', 'mifid-2',
     'Mandatory reporting of transaction costs.',
     ['mifid-1', 'aifmd'], 'Transaction-cost reporting is part of the 2014 EU rules.',
     E('I16', 70, 'transaction costs')),

    ('ORR-10', 'aml-bcbs',
     'ML/FT risk assessed at country, sector, bank and customer-relationship levels.',
     ['mifid-2', 'dodd-frank', 'aifmd'], 'Four-level ML/FT assessment is Basel Committee AML guidance.',
     E('O10', 14, 'four levels')),
    ('ORR-10', 'aml-bcbs',
     'Enhanced due diligence for politically exposed persons and frequent cross-border transfers.',
     ['mifid-2', 'dodd-frank'], 'Risk-based customer acceptance is AML guidance.',
     E('O10', 90, 'Enhanced due diligence')),
    ('ORR-10', 'aml-bcbs',
     'A bank not using IT monitoring must document why and show alternatives work.',
     ['mifid-2', 'dodd-frank'], 'Transaction monitoring expectations sit in the ML/FT guidance.',
     E('O10', 71, 'document')),
    ('ORR-10', 'aml-bcbs',
     'Uniform group-wide policies applied globally, adjusting for stricter local laws.',
     ['mifid-2', 'aifmd'], 'Cross-border group management of ML/FT risk.',
     E('O10', 135, 'Unified policies')),

    ('ORR-12', 'outsourcing-guidance',
     'Contracts with foreign providers must be governed by the institution\'s own jurisdiction\'s law.',
     ['dora', 'model-risk-guidance'], 'One of the seventeen contract provisions.',
     E('O12', 132, 'Foreign-based')),
    ('ORR-12', 'outsourcing-guidance',
     'The primary service provider is accountable for all subcontracted work.',
     ['dora', 'bcbs-opres'], 'Subcontracting provision of the guidance.',
     E('O12', 135, 'accountable')),
    ('ORR-12', 'outsourcing-guidance',
     'Due diligence on providers\' financial statements, internal controls and disaster recovery plans.',
     ['dora', 'model-risk-guidance'], 'Provider due diligence is objective (b) of the guidance.',
     E('O12', 63, 'disaster recovery')),

    ('ORR-15', 'model-risk-guidance',
     'Validation must be performed by a team independent of the model developers.',
     ['outsourcing-guidance', 'mra-1996'], 'Independent validation is a core supervisory expectation.',
     E('O15', 91, 'separate team')),
    ('ORR-15', 'model-risk-guidance',
     'Vendor models need more sensitivity analysis and benchmarking; vendors must supply details.',
     ['outsourcing-guidance', 'fsb-ai-2024'], 'Third-party model validation guidance.',
     E('O15', 147, 'sensitivity analysis')),
    ('ORR-15', 'model-risk-guidance',
     'Revalidation is required after major model changes.',
     ['mra-1996', 'frtb'], 'Outcomes analysis may force amendment and revalidation.',
     E('O15', 138, 'Revalidation')),
    ('ORR-15', 'model-risk-guidance',
     'Ongoing monitoring through process verification and benchmarking against other models.',
     ['frtb', 'mra-1996'], 'Ongoing monitoring is one of the validation elements.',
     E('O15', 117, 'Process verification')),
    ('ORR-16', 'model-risk-guidance',
     'Independent model risk review would have exposed limits of the copula CDO-pricing model.',
     ['mra-1996', 'frtb'], 'ORR-16\'s lesson: model risk management would have caught this.',
     E('O16', 72, 'CDO pricing model')),

    ('ORR-1', 'bcbs-opres',
     'Seven principles spanning governance, risk management, incident management and ICT.',
     ['dora', 'sma'], 'The BCBS issued seven resilience principles.',
     E('O1', 185, 'seven principles')),
    ('CI-8', 'dora',
     'EU act targeting ICT third-party risk, including cloud, with mandated penetration tests.',
     ['bcbs-opres', 'outsourcing-guidance'], 'CI-8 lists this among EU micro-oriented tools.',
     E('CI8', 185, 'third-party')),
    ('ORR-1', 'dora',
     'Promotes digital finance while imposing IT requirements on financial institutions.',
     ['bcbs-opres', 'bali-fintech'], 'ORR-1 describes the EU act this way (then proposed).',
     E('O1', 187, 'digital finance')),

    ('ORR-17', 'scap-2009',
     'Stress testing moves from single shocks to multi-factor macro scenarios across the whole firm.',
     ['ccar', 'eba-2011'], 'This is what the 2009 US program changed.',
     E('O17', 17, 'macro-scenarios')),
    ('ORR-17', 'scap-2009',
     'Projected losses published for each bank across eight asset classes.',
     ['ccar', 'eba-2011'], 'Bank-level disclosure across eight asset classes was the 2009 program.',
     E('O17', 133, 'eight asset classes')),
    ('ORR-17', 'scap-2009',
     'Explicit post-stress common equity threshold to confirm the bank stays viable.',
     ['ccar', 'eba-2011'], 'Capital-adequacy focus arrived with the 2009 program.',
     E('O17', 28, 'common equity threshold')),

    ('ORR-20', 'ccar',
     'Bank holding companies above $50 billion must submit capital plans for Fed evaluation.',
     ['scap-2009', 'basel-2'], 'The Capital Plan Rule, evaluated through the annual review.',
     E('O20', 12, '50 billion')),
    ('ORR-17', 'ccar',
     'Only macro-scenario results published, not bank-level results.',
     ['scap-2009', 'eba-2011'], 'The 2011 review cut transparency versus 2009; 2012 restored it.',
     E('O17', 138, 'macro-scenario results')),
    ('ORR-20', 'ccar',
     'Seven principles for an effective capital adequacy process, ending with board oversight.',
     ['basel-2', 'scap-2009'], 'The seven CAP principles apply under the Capital Plan Rule.',
     E('O20', 18, 'seven principles')),

    ('ORR-17', 'eba-2011',
     'Downloadable data and a comparison of bank versus third-party loss estimates.',
     ['scap-2009', 'ccar'], 'The 2011 European tests, notably the Irish test.',
     E('O17', 146, 'third-party loss')),

    ('CI-6', 'bcbs-crypto',
     'Higher-risk crypto exposures get a 1,250% risk weight on both long and short positions.',
     ['bali-fintech', 'basel-3-final'], 'Group 2 treatment in the proposed bank-exposure standard.',
     E('CI6', 265, '1,250')),
    ('CI-6', 'bcbs-crypto',
     'Lower-risk crypto assets weighted similarly to, or below, traditional assets.',
     ['bali-fintech', 'basel-3-final'], 'Group 1 treatment in the proposed standard.',
     E('CI6', 262, 'similar to or lower than')),
    ('CI-6', 'bali-fintech',
     'Regulators prioritise resources toward jurisdictions with significant crypto presence.',
     ['bcbs-crypto', 'fsb-ai-2024'], 'A consideration for regulators, not a bank capital rule.',
     E('CI6', 292, 'Prioritising')),
    ('CI-6', 'bali-fintech',
     'Regulators monitor developments, define the regulatory perimeter and coordinate domestically.',
     ['bcbs-crypto', 'fsb-ai-2024'], 'The agenda organises regulators themselves.',
     E('CI6', 294, 'Scope of regulation')),
    ('CI-2', 'fsb-ai-2024',
     'Regulators urged to close data gaps, update frameworks and strengthen supervision of AI.',
     ['bali-fintech', 'dora'], 'The 2024 report\'s closing agenda.',
     E('CI2', 401, 'data gaps')),
    ('CI-2', 'fsb-ai-2024',
     'Third-party dependency and service-provider concentration flagged as AI stability vulnerabilities.',
     ['dora', 'outsourcing-guidance'], 'One of the five vulnerabilities the 2024 report assesses.',
     E('CI2', 10, 'third-party')),

    # -- additions (appended to keep earlier ids stable) --
    ('CR-14', 'g20-2009',
     'Non-centrally cleared OTC derivatives attract higher capital requirements.',
     ['bilateral-margin-2011', 'amend-1995'],
     'The 2009 Pittsburgh list adds capital on non-cleared trades; the 2011 rules add margin.',
     E('C14', 249, 'higher capital requirements', 'non-centrally cleared')),
    ('ORR-17', 'eba-2011',
     'Detailed release meant to restore credibility and transparency after previous, less effective tests.',
     ['ccar', 'scap-2009'],
     'The 2011 European round followed earlier tests that had lost credibility.',
     E('O17', 148, 'restore credibility', 'less effective tests')),
]

# ---------------------------------------------------------------------------------------------
# Pairs: (reading, a, b, [(difference, evidence)])
# ---------------------------------------------------------------------------------------------
PAIRS = [
    ('MR-18', 'basel-2-5', 'frtb', [
        ('Basel 2.5 uses 99% VaR; FRTB uses expected shortfall at 97.5%.',
         E('M18', 36, 'Basel II.5', '97.5')),
        ('Basel 2.5 adds stressed VaR to current VaR; FRTB uses stressed ES.',
         E('M18', 51, 'stressed ES')),
        ('Basel 2.5 CRM used approved own models; FRTB mandates SA for securitisations.',
         E('M18', 471, 'own models', 'standardized approach')),
        ('IRC assumed constant risk via replacement; FRTB drops replacement.',
         E('M18', 452, 'constant level of risk', 'without assuming replacement')),
        ('FRTB adds liquidity horizons of 10 to 250 days by category.',
         E('M18', 157, 'liquidity horizons')),
    ]),
    ('ORR-22', 'lcr', 'nsfr', [
        ('LCR covers a 30-day stress; NSFR a one-year horizon.', E('O22', 222, '30', 'one-year')),
        ('LCR numerator is HQLA; NSFR numerator is available stable funding.',
         E('O22', 226, 'high-quality liquid assets', 'available stable funding')),
        ('LCR denominator is net cash outflows; NSFR\'s is required stable funding.',
         E('O22', 226, 'net cash outflows', 'required stable funding')),
        ('LCR phased in 2015-2019; NSFR implemented 1 January 2018.',
         E('L1', 209, '2015', '1 January 2018')),
    ]),
    ('ORR-24', 'basel-2', 'sma', [
        ('Basel II offered BIA, standardised and AMA; SMA is one approach.',
         E('O23', 54, 'single Standardized')),
        ('AMA allowed internal models; SMA is non-model-based.',
         E('O24', 122, 'internal models', 'Non-model-based')),
        ('AMA was flexible but hard to compare; SMA targets comparability and simplicity.',
         E('O24', 130, 'comparability')),
        ('BIA used 15% of gross income; SMA scales BI by 12%-18%.',
         E('O21', 515, '15')),
        ('SMA adds a loss component: 15 times average annual losses.',
         E('O24', 78, '15')),
    ]),
    ('ORR-21', 'basel-1', 'basel-2', [
        ('Basel I weighted all corporate loans 100%; Basel II weights by creditworthiness.',
         E('O21', 332, '100%', 'creditworthiness')),
        ('Basel I keyed weights to OECD status; Basel II uses credit ratings.',
         E('O21', 366, 'OECD', 'credit ratings')),
        ('Basel II adds an operational risk capital charge.', E('O21', 342, 'operational risk')),
        ('Basel II adds supervisory review (ICAAP) and market-discipline disclosure pillars.',
         E('O21', 346, 'ICAAP', 'market')),
        ('Both keep the 8% total capital ratio.', E('O21', 342, '8%')),
    ]),
    ('ORR-22', 'basel-2', 'basel-3', [
        ('Minimum total capital: 8% under Basel II, 10.5% under Basel III.',
         E('C5', 125, '8', '10.5')),
        ('Basel III eliminates Tier 3 and focuses on tangible Tier 1.',
         E('O22', 117, 'Tier 3', 'tangible')),
        ('Basel III adds conservation, countercyclical and G-SIB buffers.',
         E('O22', 196, 'G-SIBs')),
        ('Basel III adds a leverage ratio and liquidity requirements.',
         E('O22', 121, 'leverage ratios', 'Liquidity requirements')),
    ]),
    ('ORR-23', 'basel-3', 'basel-3-final', [
        ('Basel III raised capital quality and buffers; 2017 constrained internal models.',
         E('O23', 12, 'Restricting')),
        ('2017 adds a 72.5% output floor on internal-model RWA.', E('O23', 85, '72.5')),
        ('2017 adds a G-SIB leverage ratio buffer to the 3% ratio.',
         E('O23', 62, 'leverage ratio buffer')),
        ('2017 removes the IRB approach for CVA risk.', E('O23', 46, 'IRB approach for CVA')),
    ]),
    ('ORR-23', 'basel-2', 'basel-3-final', [
        ('Basel II allowed advanced IRB; 2017 bars it for large corporates and FIs.',
         E('O23', 36, 'large corporates')),
        ('Basel II floored PD at 0.03%; 2017 floors PD, LGD and EAD.',
         E('O23', 38, 'input floors')),
        ('2017 output floor is more robust than the Basel II floor.',
         E('O23', 17, 'Basel II floor')),
        ('Basel II weights by external ratings; 2017 reduces reliance on ratings.',
         E('O23', 30, 'external credit ratings')),
    ]),
    ('ORR-22', 'mra-1996', 'basel-2-5', [
        ('1996 capital is VaR-based; Basel 2.5 adds stressed VaR from 250 stressed days.',
         E('O22', 20, '250-day')),
        ('Basel 2.5 adds an IRC for downgrades and defaults.', E('O22', 66, 'Incremental Risk Charge')),
        ('Basel 2.5 adds a CRM for correlation-sensitive products.',
         E('O22', 99, 'CRM')),
        ('Both use a multiplier of 3 on average VaR in the examples.',
         E('O22', 40, 'set to 3')),
    ]),
    ('ORR-17', 'scap-2009', 'ccar', [
        ('SCAP 2009 disclosed bank-level losses; 2011 CCAR only macro results.',
         E('O17', 138, 'macro-scenario')),
        ('2012 CCAR returned to SCAP-level bank disclosure.', E('O17', 141, 'SCAP')),
        ('CCAR evaluates BHC capital plans under the Capital Plan Rule.',
         E('O20', 14, 'capital plans')),
    ]),
    ('ORR-14', 'mifid-1', 'mifid-2', [
        ('MiFID I dates from 2007; MiFID II from 2014.', E('O14', 27, '2007', '2014')),
        ('MiFID II adds pay, conflicts, independent advice and best execution.',
         E('O14', 31, 'conflicts of interest')),
        ('MiFID II was the post-2007-2009 crisis enhancement.', E('O14', 30, 'post 2007')),
    ]),
    ('LTR-3', 'bcbs-liq-2008', 'bcbs-intraday-2012', [
        ('2008 gives the general firm-level EWI list; 2012 is intraday-only.',
         E('L3', 154, 'intraday-only')),
        ('Daily maximum liquidity requirement belongs to 2012, not 2008.',
         E('L3', 160, 'Daily maximum')),
        ('Rapid asset growth is a 2008 EWI, not an intraday indicator.',
         E('L3', 154, 'rapid asset growth')),
    ]),
    ('LTR-3', 'sr-10-6', 'occ-2012', [
        ('SR 10-6 introduces event triggers and progressive states of readiness.',
         E('L3', 161, 'event triggers')),
        ('OCC 2012 targets embedded triggers in products like callable debt.',
         E('L3', 158, 'embedded triggers')),
        ('SR 10-6 is the Federal Reserve\'s; OCC 2012 is the Comptroller\'s Handbook.',
         E('L3', 145, 'Federal Reserve')),
    ]),
    ('CR-17', 'g20-2009', 'bilateral-margin-2011', [
        ('2009 mandates central clearing for standardised OTC derivatives.',
         E('C14', 247, 'mandatory central clearing')),
        ('2011 sets collateral rules for derivatives that cannot be cleared.',
         E('C17', 361, 'non-clearable')),
        ('Cleared trades absorb losses mainly via initial margin; bilateral mainly via capital.',
         E('C18', 215, 'Mainly capital', 'initial margin')),
    ]),
    ('IM-9', 'adv-act-1940', 'dodd-frank', [
        ('1940 Act exempted advisers under 15 clients; Dodd-Frank removed that exemption.',
         E('I9', 265, 'private adviser exemption')),
        ('Dodd-Frank requires SEC registration at $150m and a CCO.',
         E('I9', 173, 'Chief Compliance Officer')),
        ('Dodd-Frank adds Form PF reporting and FSOC monitoring.', E('I9', 267, 'Financial Stability Oversight')),
    ]),
    ('IM-9', 'dodd-frank', 'aifmd', [
        ('The US regulates the adviser; the EU regulates manager and leverage.',
         E('I9', 182, 'adviser')),
        ('AIFMD imposes leverage limits; ESMA interprets, member states enforce.',
         E('I9', 174, 'limits on leverage', 'ESMA')),
    ]),
    ('ORR-1', 'bcbs-opres', 'dora', [
        ('BCBS issued seven principles; DORA is an EU act, proposed in ORR-1.',
         E('O1', 186, 'seven principles', 'DORA')),
        ('DORA centres on ICT third-party and cloud risk, with penetration tests.',
         E('CI8', 186, 'penetration')),
    ]),
]


# ---------------------------------------------------------------------------------------------
def load_blocks():
    with open(BLOCKS) as fh:
        d = json.load(fh)
    out = {}
    for rid, r in d['readings'].items():
        for o in r.get('objectives', []):
            for b in o.get('blocks', []):
                sf, sl = b.get('source_file'), b.get('source_line')
                if sf and sl:
                    text = ' '.join(str(b.get(k, '')) for k in ('plain_text', 'body_latex', 'rows', 'title'))
                    out.setdefault(sf, []).append((sl, b['id'], text.lower()))
    for v in out.values():
        v.sort()
    return out


def find_block(blocks, sf, line, keywords):
    """Nearest preceding block (within 40 lines) whose text contains a keyword, else None."""
    cands = [b for b in blocks.get(sf, []) if b[0] <= line and line - b[0] <= 40]
    for sl, bid, text in reversed(cands):
        if any(k.lower() in text for k in keywords):
            return bid
    return None


def main():
    blocks = load_blocks()
    node_ids = [n['id'] for n in NODES]
    out_nodes = []
    for n in NODES:
        ev = []
        for field in ('introduced', 'restricted', 'responding_to'):
            for i, (t, e) in enumerate(n[field]):
                ev.append(dict(field=field, index=i, **e))
        links = []
        for pid, kind, basis, e in n['parents']:
            d = dict(parent=pid, kind=kind, basis=basis)
            if e:
                d.update(source_file=e['source_file'], source_line=e['source_line'],
                         keywords=e['keywords'])
            links.append(d)
        src = n['src']
        out_nodes.append({
            'id': n['id'], 'name': n['name'], 'short': n['short'], 'year': n['year'],
            'year_source': (dict(source_file=n['year_ev']['source_file'],
                                 source_line=n['year_ev']['source_line'],
                                 keywords=n['year_ev']['keywords'])
                            if n['year_ev'] else None),
            'year_note': (None if n['year'] is not None else
                          'Not dated in the notes; placed by its parents/lineage only.'),
            'lineage': n['lineage'],
            'parents': [p[0] for p in n['parents']],
            'parent_links': links,
            'reading_ids': n['readings'],
            'source_file': src['source_file'], 'source_line': src['source_line'],
            'source_keywords': src['keywords'],
            'source_block': find_block(blocks, src['source_file'], src['source_line'],
                                       src['keywords']),
            'introduced': [t for t, _ in n['introduced']],
            'restricted': [t for t, _ in n['restricted']],
            'responding_to': [t for t, _ in n['responding_to']],
            'evidence': ev,
            'summary': n['summary'],
            'aliases': n['aliases'],
            'related': n['related'],
        })
    changes = []
    counters = {}
    for rid, nid, text, decoys, why, e in CHANGES:
        counters[rid] = counters.get(rid, 0) + 1
        changes.append({
            'id': 'fn-%s-%02d' % (rid, counters[rid]), 'reading_id': rid, 'text': text,
            'node': nid, 'decoys': decoys, 'why': why,
            'source_file': e['source_file'], 'source_line': e['source_line'],
            'keywords': e['keywords'],
            'source_block': find_block(blocks, e['source_file'], e['source_line'], e['keywords']),
        })
    pairs = []
    pc = {}
    for rid, a, b, diffs in PAIRS:
        pc[rid] = pc.get(rid, 0) + 1
        pairs.append({
            'id': 'fnp-%s-%02d' % (rid, pc[rid]), 'a': a, 'b': b, 'reading_id': rid,
            'differences': [t for t, _ in diffs],
            'difference_sources': [dict(index=i, **e) for i, (_, e) in enumerate(diffs)],
        })
    doc = {
        'version': 1,
        'mechanic': 'framework-navigator',
        'notes': ('Parent kinds: explicit = the notes state the link; component = the parent '
                  'introduced the child; sequence = chronological predecessor in the lineage. '
                  'year null = the notes do not date the framework.'),
        'lineages': [{'id': i, 'label': l} for i, l in LINEAGES],
        'nodes': out_nodes,
        'changes': changes,
        'pairs': pairs,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as fh:
        json.dump(doc, fh, indent=1, ensure_ascii=False)
        fh.write('\n')
    print('wrote %s: %d nodes, %d changes, %d pairs' % (
        os.path.relpath(OUT, ROOT), len(out_nodes), len(changes), len(pairs)))
    assert len(set(node_ids)) == len(node_ids)


if __name__ == '__main__':
    main()
