// Reading titles from the notes (content/games/game-blocks.json), kept here so the Formula Gym
// can label readings without fetching that 9 MB file. Unknown ids fall back to the bare id.
export const READING_TITLES: Record<string, string> = {
  'MR-1': 'Estimating Market Risk Measures: An Introduction and Overview',
  'MR-2': 'Non-Parametric Approaches',
  'MR-3': 'Parametric Approaches (II): Extreme Value',
  'MR-4': 'Backtesting VaR',
  'MR-5': 'VaR Mapping',
  'MR-6': 'Validating Bank Holding Companies\' Value-at-Risk Models for Market Risk',
  'MR-7': 'Beyond Exceedance-Based Backtesting of VaR Models (Probability Integral Transform)',
  'MR-8': 'Correlation Basics: Definitions, Applications, and Terminology',
  'MR-9': 'Empirical Properties of Correlation: How Do Correlations Behave in the Real World?',
  'MR-10': 'Financial Correlation Modeling — Bottom-Up Approaches',
  'MR-11': 'Regression Hedging and Principal Component Analysis',
  'MR-12': 'Arbitrage Pricing with Term Structure Models',
  'MR-13': 'Expectations, Risk Premium, Convexity, and the Shape of the Term Structure',
  'MR-14': 'The Art of Term Structure Models: Drift',
  'MR-15': 'The Art of Term Structure Models: Volatility and Distribution',
  'MR-16': 'The Vasicek and Gauss+ Models',
  'MR-17': 'Volatility Smiles and Volatility Surfaces',
  'MR-18': 'Fundamental Review of the Trading Book',
  'CR-1': 'Fundamentals of Credit Risk',
  'CR-2': 'Governance',
  'CR-3': 'Credit Risk Management',
  'CR-4': 'Capital Structure in Banks',
  'CR-5': 'Introduction to Credit Risk Modeling and Assessment',
  'CR-6': 'Credit Scoring and Rating',
  'CR-7': 'Credit Scoring and Retail Credit Risk Management',
  'CR-8': 'Country Risk: Determinants, Measures, and Implications',
  'CR-9': 'Estimating Default Probabilities',
  'CR-10': 'Credit Value at Risk',
  'CR-11': 'Portfolio Credit Risk',
  'CR-12': 'Credit Risk (Hull Ch.24)',
  'CR-13': 'Credit Derivatives',
  'CR-14': 'Derivatives (Gregory Ch.2)',
  'CR-15': 'Counterparty Risk and Beyond',
  'CR-16': 'Netting, Close-out and Related Aspects',
  'CR-17': 'Margin (Collateral) and Settlement',
  'CR-18': 'Central Clearing',
  'CR-19': 'Future Value and Exposure',
  'CR-20': 'CVA',
  'CR-21': 'The Evolution of Stress Testing Counterparty Exposures',
  'CR-22': 'Structured Credit Risk',
  'CR-23': 'An Introduction to Securitisation',
  'IM-1': 'Factor Theory',
  'IM-2': 'Factors',
  'IM-3': 'Alpha (and the Low-Risk Anomaly)',
  'IM-4': 'Portfolio Construction',
  'IM-5': 'Portfolio Risk: Analytical Methods',
  'IM-6': 'VaR and Risk Budgeting in Investment Management',
  'IM-7': 'Portfolio Performance Evaluation',
  'IM-8': 'Hedge Fund Investment Strategies',
  'IM-9': 'Risk, Regulation and Organizational Structure',
  'IM-10': 'The Rise and Risks of Private Credit',
  'IM-11': 'Private Markets Investing',
  'IM-12': 'Performing Due Diligence on Specific Managers and Funds',
  'IM-13': 'Distress Symptoms and Remedies',
  'IM-14': 'Madoff: A Riot of Red Flags',
  'IM-15': 'Market-Driven Scenarios: An Approach for Plausible Scenario Construction',
  'IM-16': 'Liquidity Risk Management',
  'IM-17': 'Illiquid Assets',
  'LTR-1': 'Liquidity Risk',
  'LTR-2': 'Liquidity and Leverage',
  'LTR-3': 'Early Warning Indicators',
  'LTR-4': 'The Investment Function in Financial-Services Management',
  'LTR-5': 'Liquidity and Reserves Management: Strategies and Policies',
  'LTR-6': 'Intraday Liquidity Risk Management',
  'LTR-7': 'Monitoring Liquidity',
  'LTR-8': 'The Failure Mechanics of Dealer Banks',
  'LTR-9': 'Liquidity Stress Testing',
  'LTR-10': 'Liquidity Risk Reporting and Stress Testing',
  'LTR-11': 'Contingency Funding Planning',
  'LTR-12': 'Managing Non-Deposit Liabilities',
  'LTR-13': 'Repurchase Agreements and Financing',
  'LTR-14': 'Liquidity Transfer Pricing: A Guide to Better Practice',
  'LTR-15': 'The US Dollar Shortage in Global Banking and the International Policy Response',
  'LTR-16': 'Covered Interest Parity Lost: Understanding the Cross-Currency Basis',
  'LTR-17': 'Risk Management for Changing Interest Rates: Asset-Liability Management and Duration Techniques',
  'ORR-1': 'Introduction to Operational Risk and Resilience',
  'ORR-2': 'Risk Governance',
  'ORR-3': 'Risk Identification',
  'ORR-4': 'Risk Measurement and Assessment',
  'ORR-5': 'Risk Mitigation',
  'ORR-6': 'Risk Reporting',
  'ORR-7': 'Integrated Risk Management',
  'ORR-8': 'Cyber-resilience: Range of Practices',
  'ORR-9': 'Case Study: Cybersecurity and Information Security Risks',
  'ORR-10': 'Sound Management of Risks Related to Money Laundering and Financing of Terrorism',
  'ORR-11': 'Case Study: Financial Crime and Fraud',
  'ORR-12': 'Guidance on Managing Outsourcing Risk',
  'ORR-13': 'Case Study: Third-Party Risk Management',
  'ORR-14': 'Case Study: Investor Protection and Compliance Risks',
  'ORR-15': 'Supervisory Guidance on Model Risk Management',
  'ORR-16': 'Case Study: Model Risk and Model Validation',
  'ORR-17': 'Stress Testing Banks',
  'ORR-18': 'Risk Capital Attribution and Risk-Adjusted Performance Measurement',
  'ORR-19': 'Range of Practices and Issues in Economic Capital Frameworks',
  'ORR-20': 'Capital Planning at Large Bank Holding Companies',
  'ORR-21': 'Capital Regulation Before the Global Financial Crisis',
  'ORR-22': 'Solvency, Liquidity, and Other Regulation After the GFC',
  'ORR-23': 'High-Level Summary of Basel III Reforms',
  'ORR-24': 'Basel III: Finalising Post-Crisis Reforms',
  'CI-1': 'Advances in Artificial Intelligence: Implications for Capital Markets Activities',
  'CI-2': 'The Financial Stability Implications of Artificial Intelligence',
  'CI-3': 'The Global Drivers of Private Credit',
  'CI-4': 'Global Financial Stability Report, Chapter 2: Geopolitical Risk',
  'CI-5': 'Monetary and Fiscal Policy: Safeguarding Stability and Trust',
  'CI-6': 'Regulating the Crypto Ecosystem: The Case of Unbacked Crypto Assets',
  'CI-7': 'Tokenization and Financial Market Inefficiencies',
  'CI-8': 'Digital Resilience and Financial Stability: The Quest for Policy Tools in the Financial Sector',
};
